[WIP] Add cheat sheet to the docs
alpaka-group/alpaka pull request #1057
Opened 2020-06-30 13:55 UTC by SimeonEhrig

# About
- The cheat sheet is written with reStructed text
- It can integrate in the website
- Can compiled to pdf a compact format with with `rst2pdf`

# Todo
- [ ] integration in Sphinx Doc build
- [ ] add build instruction for the cheatsheet pdf to the Sphinx Doc

2020-06-30 13:56 UTC, SimeonEhrig commented
Output of commit 4ab7041a3d530089708751ee23a88bbb9124efb4

[cheatsheet.pdf](https://github.com/alpaka-group/alpaka/files/4852292/cheatsheet.pdf)

2020-07-01 14:25 UTC, SimeonEhrig commented
@sbastrakov If you have not already done so, please check the content that I did not make an error in transferring the content from your version.

2020-07-01 15:04 UTC, sbastrakov requested changes
Almost everything is fine, just a couple of small things in review comments.

2020-07-01 15:04 UTC, sbastrakov commented on docs/cheatsheet/README.md
> +The style cheat (cheatsheet.style) was original develop by Roberto Alsina.
Please replace `original develop` with `originally developed`.
I am also not sure about `style cheat`, perhaps you meant something like `cheat sheet style`?

2020-07-01 15:04 UTC, sbastrakov commented on docs/source/usage/cheatsheet.rst
> +The Kernel Execution
I would remove `The` (and it was not in my version).

2020-07-01 15:04 UTC, sbastrakov commented on docs/source/usage/cheatsheet.rst
> +``ALPAKA_FN_ACC`` is required for kernels and functions called inside, acc is mandatory first parameter, its type is the template parameter
Perhaps put acc as code?

2020-07-01 15:04 UTC, sbastrakov commented on docs/source/usage/cheatsheet.rst
> +					       OperationHierarchy);
This line seems unaligned to the previous one

2020-07-01 15:04 UTC, sbastrakov commented on docs/source/usage/cheatsheet.rst
> +     auto distribution = rand::distribution::createNormalReal<double>(acc));
This is also a mistake in my document, should be one `)` in the end, not two.

2020-07-01 15:04 UTC, sbastrakov commented on docs/source/usage/cheatsheet.rst
> +  OperationHierarchy (all in hierarchy):
I like this change to put stuff in the namespace, but then the brackets (all in ...) is not necessary.

2020-07-01 15:26 UTC, sbastrakov commented
Also, I think it's fair if I am a co-author of this PR since the original cheat sheet content authorship. Or you can optionally separate your style changes in a separate commit, and add the contents as another, co-authored, one.

2020-07-02 07:13 UTC, SimeonEhrig commented on docs/source/usage/cheatsheet.rst
> +``ALPAKA_FN_ACC`` is required for kernels and functions called inside, acc is mandatory first parameter, its type is the template parameter
I highlighted the acc as code

2020-07-02 07:16 UTC, SimeonEhrig commented
> Also, I think it's fair if I am a co-author of this PR since the original cheat sheet content authorship. Or you can optionally separate your style changes in a separate commit, and add the contents as another one, that is co-authored.

Yes, it's totally fair, that you are the co-author. I have never tried to add an co-author before, so I hope my solution is fine (see commit message). If you have better solution, please write.

2020-07-02 07:20 UTC, sbastrakov commented
@SimeonEhrig I believe there should be a new line before Co-author line. Or somehow this one did not work.

2020-07-02 07:27 UTC, sbastrakov commented
Ah, and I use my personal email for github, not work one. Don't want to post it here, but you can see in the log.

2020-07-02 08:35 UTC, sbastrakov approved these changes

2020-07-03 09:06 UTC, sbastrakov commented
I contributed to this PR, so would ask for an additional review.

2020-07-04 12:14 UTC, BenjaminW3 approved these changes

2020-07-04 12:14 UTC, merged