Example monte-carlo-integration
alpaka-group/alpaka pull request #1106
Opened 2020-07-29 16:43 UTC by jkrude

This is an _alpaka_ implementation of the **monte-carlo-integration** method.

The example targets the topics:
- (pseudo) random-number-generation
- atomic functions

The code is based on a cpu-prototype by @sbastrakov.

2020-07-29 17:37 UTC, BenjaminW3 commented on example/monteCarloIntegration/src/monteCarloIntegration.cpp
> +//! This functor defines the function for which the integral is to computed.
```suggestion
//! This functor defines the function for which the integral is to be computed.
```

2020-08-11 05:35 UTC, psychocoderHPC approved these changes

2020-08-11 05:39 UTC, psychocoderHPC requested changes

2020-08-11 05:39 UTC, psychocoderHPC commented on example/monteCarloIntegration/src/monteCarloIntegration.cpp
> +#include <typeinfo>
please include `<cstdlib>` for `EXIT_SUCCESS` and `EXIT_FAILURE`

2020-08-11 07:18 UTC, sbastrakov commented on example/monteCarloIntegration/src/monteCarloIntegration.cpp
> +/* Copyright 2019 Benjamin Worpitz, Sergei Bastrakov, Jakob Krude
I think the year should be 2020?

2020-08-11 07:19 UTC, sbastrakov commented on example/monteCarloIntegration/src/monteCarloIntegration.cpp
> +            (1 - x * x));
1.0f is a little cleaner than 1.

2020-08-11 07:22 UTC, sbastrakov commented on example/monteCarloIntegration/src/monteCarloIntegration.cpp
> +            0);
Perhaps it is easier to make `linearizedGlobalThreadIdx ` be a single number, by adding `[0]` at line 79 before `;`.

2020-08-11 07:24 UTC, sbastrakov requested changes

2020-08-11 07:24 UTC, sbastrakov commented on example/monteCarloIntegration/src/monteCarloIntegration.cpp
> +        for(size_t i = globalThreadIdx[0];
I think this is a mistake and should be `linearizedGlobalThreadIdx[0]` (or without `[0]` with my earlier suggestion) instead.

2020-08-11 07:24 UTC, sbastrakov commented on example/monteCarloIntegration/src/monteCarloIntegration.cpp
> +    std::cout << "global count: " << globalCount << "\n";
I think this output could be removed. As for a user the latter output of exact and actual result is informative, but this one is not necessarily.

2020-08-17 09:41 UTC, sbastrakov submitted a review, later dismissed

2020-08-22 11:30 UTC, BenjaminW3 commented on example/monteCarloIntegration/src/monteCarloIntegration.cpp
> +        // For simplicity the interval is fixed at [0,1].
Documentation of `createUniformReal` says `[0.0, 1.0)`.

2020-08-24 07:25 UTC, sbastrakov commented on example/monteCarloIntegration/src/monteCarloIntegration.cpp
> +        // For simplicity the interval is fixed at [0,1].
Yes. So for Monte-Carlo does not matter, but better be precise at the comment.

2020-09-03 14:11 UTC, BenjaminW3 approved these changes

2020-09-03 14:11 UTC, merged