Remove some mem related namespaces
alpaka-group/alpaka pull request #1173
Opened 2020-10-09 12:44 UTC by bernhardmgruber

remove namespace alpaka::buf::cpu
remove namespace alpaka::buf::omp5
remove namespace alpaka::buf
remove namespace alpaka::alloc
remove namespace alpaka::view::uniform_cuda_hip

2020-10-09 12:52 UTC, bernhardmgruber commented
With the removal of the `buf` namespace, we now have two functions `alloc`:

1. `auto alpaka::alloc(TAlloc const & alloc, std::size_t const & sizeElems) -> T *`
    Is a kind of aligned memory allocator. The returned pointer must be passed to `alpaka::free()`.
2. `auto alpaka::alloc(TDev const & dev, TExtent const & extent = TExtent())`
    Creates buffers, which destroy themselves using their dtor.

I propose to rename one of them. Either the first one to `alpaka::malloc()` or the second one to `alpaka::allocBuf` or `alpaka::createBuf`. What do you think?

2020-10-09 13:02 UTC, sbastrakov commented
Or maybe rename them both? As otherwise the remaining `alloc` may be still confusing.

2020-10-12 06:48 UTC, psychocoderHPC requested changes
There are some compile issues in the CI: e.g. https://github.com/alpaka-group/alpaka/pull/1173/checks?check_run_id=1232144344#step:5:4380

2020-10-12 13:02 UTC, psychocoderHPC approved these changes

2020-10-12 13:03 UTC, merged