[clang-format] Add .clang-format file
alpaka-group/alpaka pull request #1204
Opened 2020-11-10 13:23 UTC by j-stephan

This is the .clang-format file used for #1194 and #1203.

Application: From the top-level alpaka directory, execute

```bash
find example include test -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i --style=file
```
I'm not certain about the best place in the docs to include the command. Any suggestions?

2020-11-11 09:05 UTC, sbastrakov commented
I think [here](https://alpaka.readthedocs.io/en/latest/dev/style.html) is a fitting place

2020-11-11 09:51 UTC, SimeonEhrig commented
> I think [here](https://alpaka.readthedocs.io/en/latest/dev/style.html) is a fitting place

That's a good idea. Overworking this section should also be part of this PR.

2020-11-11 09:53 UTC, sbastrakov commented
Well, yes. And I think it can become just very brief: point to the format file, and have a line of how to apply it

2020-11-11 17:18 UTC, BenjaminW3 commented
I think half of what is documented is not yet handled by clang-format so we should keep those parts.
I think `Comments`, `Braces`, `Indentation` and `Spaces` can be deleted.

2020-11-13 15:40 UTC, bernhardmgruber commented
Regarding a clang-format command: Shouldn't this be part of the CONTRIBUTIND.md as its done for mallocMC and LLAMA? Also for consistency.

See:
https://github.com/alpaka-group/mallocMC/blob/dev/CONTRIBUTING.md
https://github.com/alpaka-group/llama/blob/master/CONTRIBUTING.md

2020-11-14 16:39 UTC, bernhardmgruber submitted a review, later dismissed

2020-11-17 09:38 UTC, psychocoderHPC approved these changes

2020-11-17 09:52 UTC, j-stephan commented
Please don't merge yet, we need to wait for #1203.

2020-11-17 13:35 UTC, psychocoderHPC requested changes

2020-11-17 13:35 UTC, psychocoderHPC commented on .clang-format
> +AlignOperands: DontAlign
Somehow I get an error when I try to use this style file with clang-format-11 or clang-format-10

```
YAML:14:16: error: invalid boolean
AlignOperands: DontAlign
               ^~~~~~~~~
```

2020-11-17 13:37 UTC, psychocoderHPC commented on .clang-format
> +IndentExternBlock: AfterExternBlock
This is unknown
```
YAML:53:20: error: unknown key 'IndentExternBlock'
IndentExternBlock: AfterExternBlock
```

2020-11-17 13:38 UTC, psychocoderHPC commented
@j-stephan  Which clang format version is required? Do you test this file with an already released clang?

2020-11-17 13:39 UTC, psychocoderHPC commented on docs/source/dev/style.rst
> +  find example include test -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i --style=file
The command should contain the clang version e.g. `clang-format-11`

2020-11-17 13:40 UTC, psychocoderHPC commented on .clang-format
> +AllowShortEnumsOnASingleLine: false
git clang-format-11
YAML:21:31: error: unknown key 'AllowShortEnumsOnASingleLine'
AllowShortEnumsOnASingleLine: false

2020-11-17 13:41 UTC, psychocoderHPC commented on .clang-format
> +IndentCaseBlocks: true
```
YAML:51:19: error: unknown key 'IndentCaseBlocks'
IndentCaseBlocks: true
```

2020-11-17 13:42 UTC, psychocoderHPC commented on .clang-format
> +AlignConsecutiveBitFields: false
```
YAML:10:28: error: unknown key 'AlignConsecutiveBitFields'
AlignConsecutiveBitFields: false
```

2020-11-17 13:42 UTC, psychocoderHPC commented on .clang-format
> +IndentExternBlock: AfterExternBlock
This is for clang 12

2020-11-17 15:52 UTC, psychocoderHPC approved these changes

2020-11-20 07:14 UTC, psychocoderHPC commented
I will merge this that we can at least format our code with `git clang-format-11`

2020-11-20 07:14 UTC, merged