CUDA 11.3 support
alpaka-group/alpaka pull request #1295
Opened 2021-04-19 17:15 UTC by psychocoderHPC

fix #1293 

- fix compile issues shown up with CUDA 11.3
- CI add CUDA 11.3
- update documentation

2021-04-19 18:01 UTC, BenjaminW3 requested changes

2021-04-19 18:01 UTC, BenjaminW3 commented on .github/workflows/ci.yml
> +#   [ON] ALPAKA_CUDA_VERSION                    : {9.2, 10.0, 10.1, 10.2, 11.0, 11.1, 11.2, 11.3}
We still test 9.0 and 9.1. Why did you delete them from the list?

2021-04-19 18:01 UTC, BenjaminW3 commented on .github/workflows/ci.yml
> +
Shouldn't this block be directly above the new `# nvcc + clang++` block below?

2021-04-19 19:19 UTC, psychocoderHPC commented on .github/workflows/ci.yml
> +#   [ON] ALPAKA_CUDA_VERSION                    : {9.2, 10.0, 10.1, 10.2, 11.0, 11.1, 11.2, 11.3}
I thought we need 9.2+, I will check again

2021-04-19 19:20 UTC, psychocoderHPC commented on .github/workflows/ci.yml
> +
Thanks, maybe I messed up with the order, I will check it again.

2021-04-20 09:33 UTC, sbastrakov commented
Removed 0.6.1 project as on the VC we decided it will go to 0.7.0.

2021-04-20 10:51 UTC, psychocoderHPC commented
> Removed 0.6.1 project as on the VC we decided it will go to 0.7.0 and not be backported.

Note: we decided in the developer meeting to aim for alpaka 0.7.0 feature freeze begin of May (2021) and to release 0.7.0 (with CUDA 11.3 support) latest around two months later.

2021-04-23 14:12 UTC, sbastrakov approved these changes

2021-04-23 14:13 UTC, merged