Rename "generator" to "engine" in rand
alpaka-group/alpaka pull request #1318
Opened 2021-05-25 09:36 UTC by sliwowitz

As discussed in an earlier meeting, *engine* is a better name than *generator*. It's also consistent with the STL which refers to these as engines (even though it does not use such a namespace directly).

2021-05-25 09:59 UTC, j-stephan requested changes
The changes look good so far, but the test cases need to be updated as well.

Could you also squash your commits into one?

2021-05-25 10:10 UTC, sliwowitz commented
> The changes look good so far, but the test cases need to be updated as well.

Sorry, forgot about these. fixing it now.

> Could you also squash your commits into one?

Sure. I thought it would be squashed after the review upon merging to develop. Is it possible to squash on the go as I add further commits to this already opened PR?

2021-05-25 11:16 UTC, j-stephan commented
Yes, you can squash them once the PR is ready to be merged.

2021-05-25 17:14 UTC, bernhardmgruber approved these changes

2021-05-26 09:24 UTC, j-stephan approved these changes
LGTM.

2021-05-26 09:26 UTC, merged