Fix bug, if alpaka_add_library() and Clang as CUDA compiler is used together
alpaka-group/alpaka pull request #1363
Opened 2021-07-27 13:48 UTC by SimeonEhrig

I tested the code with the modernized cmake for cupla: https://github.com/alpaka-group/cupla/pull/203
It uses alpaka_add_library, if the examples are build.

It's related to the issue #1359

2021-07-30 07:09 UTC, j-stephan submitted a review, later dismissed

2021-07-30 07:12 UTC, j-stephan commented
@alpaka-group/alpaka-maintainers 

Since this PR has no problems we could merge this. However, this change only affects our `0.6.1` branch (and older versions which we don't care about) because they way this is handled has changed with `0.7.0`.

1. Do we want to incorporate this PR into 0.6.1? The issue is rather exotic since nobody has found it before and I doubt many people care about this combination of compilers + options.
2. If we want to merge the PR, do we need to bump the version number to 0.6.2?

Until we have found a consensus here please DO NOT MERGE this PR.

2021-07-30 11:38 UTC, psychocoderHPC commented
Wait 0.6.1 branch should be deleted, I forget to delete this branch. The release is already out and merging something into the 0.6.1 branch will have no effect.

2021-07-30 11:48 UTC, psychocoderHPC commented
I redirected this PR against 0.6.2 and opened also a branch 0.6.2, removed the 0.6.1 milestone and opened a project 0.6.2

2021-07-30 13:58 UTC, psychocoderHPC commented
@j-stephan This is broken in 0.7.0 too and must be backported on Monday!

2021-07-30 14:40 UTC, psychocoderHPC commented
@SimeonEhrig could it be that the order of arguments is wrong for HIP too?

2021-08-02 07:00 UTC, psychocoderHPC requested changes

2021-08-02 07:00 UTC, psychocoderHPC commented on cmake/addLibrary.cmake
> +                ${sourceFileNames}
PLease move source files as last argument to fulfill the Cmake description https://cmake.org/cmake/help/latest/command/add_library.html

2021-08-02 08:19 UTC, SimeonEhrig commented
> @SimeonEhrig could it be that the order of arguments is wrong for HIP too?

@psychocoderHPC Looks like so. I will test it. But if HIP is also affected, we need to fix it in `alpaka 0.6.2` and `0.7.0`. Should I open a second PR or do you pull somehow to the current dev branch and backport it? Could be complicated because the cmake was strong changed since `0.6.1`.

2021-08-02 10:36 UTC, j-stephan commented
>  But if HIP is also affected, we need to fix it in alpaka 0.6.2 and 0.7.0. Should I open a second PR or do you pull somehow to the current dev branch and backport it? Could be complicated because the cmake was strong changed since 0.6.1.

Why would we need a second PR? Can't this be changed as part of this PR, too?

2021-08-02 10:36 UTC, j-stephan commented
Please also update the author list and copyright year!

2021-08-02 12:23 UTC, SimeonEhrig commented
> > But if HIP is also affected, we need to fix it in alpaka 0.6.2 and 0.7.0. Should I open a second PR or do you pull somehow to the current dev branch and backport it? Could be complicated because the cmake was strong changed since 0.6.1.
> 
> Why would we need a second PR? Can't this be changed as part of this PR, too?

Okay, it became a little bit tricky. To make it short. This bug does not affect HIP, because the API of `hip_add_library` is different to `add_library` but @psychocoderHPC recognized correctly, that this bug also affected version `0.7.0`. To not slow down the release of alpaka `0.7.0`, @psychocoderHPC suggested that I open extra PRs for the `develop` and the `0.7.0-rc1` branch.

2021-08-02 12:36 UTC, j-stephan approved these changes

2021-08-03 09:15 UTC, psychocoderHPC approved these changes

2021-08-03 09:16 UTC, merged