Update Zenodo file [develop]
alpaka-group/alpaka pull request #1371
Opened 2021-08-02 14:32 UTC by j-stephan

2021-08-03 09:27 UTC, psychocoderHPC requested changes

2021-08-03 09:27 UTC, psychocoderHPC commented on .zenodo.json
> +      "affilitation": "Oak Ridge National Laboratory",
type must be `affiliation`

2021-08-05 11:58 UTC, psychocoderHPC commented on .zenodo.json
> +      "affilitation": "Oak Ridge National Laboratory",
@j-stephan could you please fix ths PR

2021-08-05 12:41 UTC, j-stephan commented on .zenodo.json
> +      "affilitation": "Oak Ridge National Laboratory",
Done.

2021-08-06 06:38 UTC, merged