Add special handling for serial CPU memfence
alpaka-group/alpaka pull request #1422
Opened 2021-10-13 11:45 UTC by j-stephan

Closes #1403.

2021-10-13 12:04 UTC, bernhardmgruber requested changes

2021-10-13 12:04 UTC, bernhardmgruber commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                static std::atomic<int> dummy{42};
A local `static` variable with an initializer will implicitely introduce an atomic test into this function, which might be additional overhead. That variable should be moved outside the function, but I guess that would require C++17 to stay header-only.

2021-10-13 12:04 UTC, bernhardmgruber commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                /* Enable device fences because we may want to synchronize with other (serial) kernels. */
Are you sure? Do memory fences in CUDA kernels synchronize with other CUDA kernels? The way I interpret the CUDA programming guide, there are no guarantees between kernels. So I would stick to the same behavior on CPU kernels and have this function empty.

2021-10-13 12:04 UTC, bernhardmgruber commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                /* Enable device fences because we may want to synchronize with other (serial) kernels. */
I interpret `memory_scope::Device` as kernel wide, as the CUDA implementation uses `__threadfence` and not `__threadfence_system`.

2021-10-13 12:15 UTC, j-stephan commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                /* Enable device fences because we may want to synchronize with other (serial) kernels. */
CUDA's `__threadfence()` is observed by all threads in the device, not a single kernel. See the corresponding section here: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#memory-fence-functions

Note that it explicitly talks about `device`, not `kernel`.

Which makes sense - how would you guarantee observability across all kernel threads without guaranteeing the same on the whole device? You don't know on which SM your blocks are going to execute, you must make it observable on the entire device.

2021-10-13 12:16 UTC, j-stephan commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                static std::atomic<int> dummy{42};
Do you suggest a C++14 conforming change or is this something we need to keep in mind?

2021-10-13 12:31 UTC, bernhardmgruber commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                /* Enable device fences because we may want to synchronize with other (serial) kernels. */
I think I got a bit confused by this SO answer: https://stackoverflow.com/a/6546246/2406044. Re-reading the programming guide actually looks like `__threadfence` will synchronize between kernels on the same device. So I assume the fence on the CPU is needed to have the same behavior.

2021-10-13 12:33 UTC, j-stephan commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                /* Enable device fences because we may want to synchronize with other (serial) kernels. */
> So I assume the fence on the CPU is needed to have the same behavior.

Yup. This behaviour was also suggested by CMS, so it seems intuitive from a user POV.

2021-10-13 12:48 UTC, bernhardmgruber commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                static std::atomic<int> dummy{42};
I suggested a simplification and performance improvement with C++17.

2021-10-13 12:49 UTC, bernhardmgruber commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                dummy.store(x, std::memory_order_relaxed);
Have you actually checked the correctness of your implementation? This code compiles down to an empty function with clang: https://godbolt.org/z/a6nbes7xz

2021-10-13 15:31 UTC, j-stephan commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                dummy.store(x, std::memory_order_relaxed);
Yes. This is because `std::memory_order_acq_rel` does not correspond to an actual hardware instruction on x86. If you change the architecture to something else you will see a non-empty function. Example for RISC-V:

```
mem_fence():                          # @mem_fence()
        fence.tso       
        ret
```

2021-10-13 15:32 UTC, j-stephan commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                static std::atomic<int> dummy{42};
Okay. Since we are currently on C++14 I guess this is resolved for now?

2021-10-13 15:57 UTC, bernhardmgruber commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                dummy.store(x, std::memory_order_relaxed);
Fair enough, but the body is also empty for ARM64: https://godbolt.org/z/dW7En6qq3 Is that correct too? I wonder if clang is smart and realizes that the atomic is not visible outside the function and the code inside therefore has no visible side effects.

2021-10-13 16:02 UTC, j-stephan commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                dummy.store(x, std::memory_order_relaxed);
It is not empty. `dmb ish` is a memory barrier. https://developer.arm.com/documentation/100941/0100/Barriers

2021-10-13 16:10 UTC, bernhardmgruber commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                static std::atomic<int> dummy{42};
Maybe. I don't see the lock for the initialization of the static variable being created in godbolt. But I guess it's fine because the integer will be put preinitialized in the data segment. I still think there is something wrong with this code, but let's discuss this in the thread below.

2021-10-13 16:42 UTC, bernhardmgruber commented on include/alpaka/mem/fence/MemFenceCpuSerial.hpp
> +                dummy.store(x, std::memory_order_relaxed);
Oh. Then I must have misread the tooltop in godbolt. Sorry!

2021-10-13 16:50 UTC, bernhardmgruber commented
I am still wondering whether the implementation is correct, so I created this little test based on the alpaka documentation:
```c++
void mem_fence() {
    static std::atomic<int> dummy{42};
    auto x = dummy.load(std::memory_order_relaxed);
    std::atomic_thread_fence(std::memory_order_acq_rel);
    dummy.store(x, std::memory_order_relaxed);
}

unsigned vars[2]{2, 1};

void a() {
    vars[0]++;
    mem_fence();
    vars[1]++;
}

void b() {
    auto const a = vars[0];
    mem_fence();
    auto const b = vars[1];
    if(a == b) report_fail(a, b);
}

constexpr auto n = 1000000;
int main() {
    std::thread ta([]{ for (auto i = 0; i < n; i++) a(); });
    std::thread tb([]{ for (auto i = 0; i < n; i++) b(); });
    ta.join();
    tb.join();
}
```
Godbolt: https://godbolt.org/z/s481MEojd

I would argue that `report_fail` should never be called, as `a` should always be ahead of `b`. However, if you press recompile on Godbolt a couple of times, you can see that `report_fail` is called many times. Maybe my example is be wrong. But I still think there is an issue.

2021-10-13 17:09 UTC, j-stephan commented
Remember that we are talking about memory fences, not synchronization. The memory fence in your example guarantees that `vars[0]++` happens before `var[1]++` and that `a` is loaded before `b`. There is no relationship between `vars[0]++` and the loading of `a`.

For an actual test case you need to switch the loading of `a`and `b` as follows:

```c++
void b()
{
    auto const a = vars[1];
    mem_fence();
    auto const b = vars[0];
    if(a == b) report_fail(a, b);
}
```

Thanks to the memory fence it is always ensured that `vars[0]++` happens before `vars[1]++` and also before `b` is loaded. Thus `a` and `b` can never be the same.

2021-10-14 06:07 UTC, j-stephan commented
Ready to merge.

2021-10-14 09:27 UTC, psychocoderHPC approved these changes

2021-10-14 09:47 UTC, bernhardmgruber commented
@j-stephan I think I confused something there indeed. Thank you for the explanation!

2021-10-14 09:47 UTC, bernhardmgruber approved these changes

2021-10-14 09:47 UTC, merged