Atomic tests enabled and fix for float/double
alpaka-group/alpaka pull request #1431
Opened 2021-10-25 14:07 UTC by tonydp03

This Pull request enables back all the atomic tests. The 8- and 16-bit tests are skipped for the CUDA/HIP backend; the float and double tests for atomics are re-enabled but not run for bitwise operations (and, or, xor).

2021-10-25 20:55 UTC, bernhardmgruber requested changes
I think you did not run clang-format on your PR. Please do so. I have seen you use VSCode. It should have a formatting hotkey as well, see e.g.: https://code.visualstudio.com/docs/cpp/cpp-ide.
Post-commit, you can run `git clang-format HEAD~1` to reformat the changes from the last commit, then amend and force push.

2021-10-25 20:55 UTC, bernhardmgruber commented on test/unit/atomic/src/AtomicTest.cpp
> +
Please don't add any unnecessary whitespace.

2021-10-26 09:11 UTC, bernhardmgruber commented
Regarding the failing tests. You might need to disable the floating point comparison warnings around the offending lines:
```c++
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wfloat-equal"
    ...
#pragma GCC diagnostic pop
```

2021-10-27 14:12 UTC, bernhardmgruber requested changes

2021-10-27 14:12 UTC, bernhardmgruber commented on test/unit/atomic/src/AtomicTest.cpp
> +#    pragma GCC diagnostic pop
Are you sure this is required here? There is no float comparison involved here.

2021-10-27 14:12 UTC, bernhardmgruber commented on test/unit/atomic/src/AtomicTest.cpp
> +#    pragma GCC diagnostic pop
See above.

2021-10-28 08:09 UTC, tonydp03 commented on test/unit/atomic/src/AtomicTest.cpp
> +#    pragma GCC diagnostic pop
I put it everywhere around ALPAKA_CHECK to see if it worked - I was wondering if those pragmas were working for every compiler, but as far as I see, they don't. So should we put other pragmas around those lines, for all the compilers? Or maybe it's better to modify the library `Op.hpp` such that whenever there's a comparison warnings should be ignored if it's between floating point numbers?

2021-10-28 08:36 UTC, tonydp03 commented on test/unit/atomic/src/AtomicTest.cpp
> +#    pragma GCC diagnostic pop
Like it is done in

https://github.com/alpaka-group/alpaka/blob/878dc184d92bba0bbbf6379e5b9886142aed7e9a/include/alpaka/atomic/Op.hpp#L190-L197

At the end, in the Op.hpp library the comparison happens only in AtomicCas and atomicDec if I saw correctly. A possibility would be to add pragmas around those lines only, but for every compiler?

2021-10-28 08:39 UTC, bernhardmgruber commented on test/unit/atomic/src/AtomicTest.cpp
> +#    pragma GCC diagnostic pop
Well, that's a good first test locally. But please apply them only where they are really needed.
As you said you are going needed to `#ifdef` them for the right compiler, like:
```c++
#if BOOST_COMP_GNUC
#    pragma GCC diagnostic push
#    pragma GCC diagnostic ignored "-Wfloat-equal"
#endif
...
#if BOOST_COMP_GNUC
#    pragma GCC diagnostic pop
#endif
```
Also check if that works, because I think clang is also producing the warning.

I think we should not suppress the warning in general, because it is useful in other places. But we can debate this. @j-stephan?

2021-10-28 09:32 UTC, tonydp03 commented on test/unit/atomic/src/AtomicTest.cpp
> +#    pragma GCC diagnostic pop
Maybe we should discuss this offline and see if there could be a better solution rather than adding all this stuff in the code just to suppress warnings?

2021-10-29 09:02 UTC, tonydp03 commented on test/unit/atomic/src/AtomicTest.cpp
> +#    pragma GCC diagnostic pop
We might want to comment out these tests for float?
https://github.com/alpaka-group/alpaka/blob/0dcc191e502509fa658600a4abaed49711fff0a8/test/unit/atomic/src/AtomicTest.cpp#L317-L325
It seems that `atomicInc`, `atomicDec` and `atomicCas` are not supported with floats and they perform float comparison, which is what it might cause the warning. But we would still need pragmas for the ALPAKA_CHECK with the float comparisons).

2021-10-29 09:09 UTC, bernhardmgruber commented on test/unit/atomic/src/AtomicTest.cpp
> +#    pragma GCC diagnostic pop
Sure, comment out these atomics for floating point types! Add the pragmas in the other places please.

2021-11-02 16:31 UTC, bernhardmgruber commented
You may want to replace all the diagnostic disabling by a new function that @sliwowitz will bring in soon: #1440.

2021-11-08 15:18 UTC, tonydp03 commented
> You may want to replace all the diagnostic disabling by a new function that @sliwowitz will bring in soon: #1440.

I just saw it's already been merged. What would be the best way, just closing the repo and adding the atomic test changes to the clean repository to open a new PR? (Since this is a draft one...)

2021-11-08 15:24 UTC, bernhardmgruber commented
> > You may want to replace all the diagnostic disabling by a new function that @sliwowitz will bring in soon: #1440.
> 
> I just saw it's already been merged. What would be the best way, just closing the repo and adding the atomic test changes to the clean repository to open a new PR? (Since this is a draft one...)

Rebase on `develop` and sort out potential conflicts, then remove the pragmas and use @sliwowitz's function. You might also want to start new from `develop` and apply the non-pragma changes and then. In any case, I would force push to the same remote branch name here and continue on this PR.

2021-11-10 14:36 UTC, bernhardmgruber requested changes

2021-11-10 14:36 UTC, bernhardmgruber commented on test/unit/atomic/src/AtomicTest.cpp
> +}
```suggestion
ALPAKA_FN_INLINE ALPAKA_FN_HOST_ACC bool equals(float a, float b)
{
    return alpaka::math::floatEqualExactNoWarning(a, b);
}
```

2021-11-10 14:36 UTC, bernhardmgruber commented on test/unit/atomic/src/AtomicTest.cpp
> +}
```suggestion
ALPAKA_FN_INLINE ALPAKA_FN_HOST_ACC bool equals(double a, double b)
{
    return alpaka::math::floatEqualExactNoWarning(a, b);
}
```

2021-11-10 14:36 UTC, bernhardmgruber commented on test/unit/atomic/src/AtomicTest.cpp
> +}
prefer function overload to function template specialization.

2021-11-10 14:51 UTC, tonydp03 commented on test/unit/atomic/src/AtomicTest.cpp
> +}
Changes committed and pushed.

2021-11-10 14:59 UTC, bernhardmgruber submitted a review, later dismissed

2021-11-11 09:21 UTC, bernhardmgruber commented
@jkelling the only failing test is with nvc++ and I don't get the error message. Could you maybe have a look please? Thx!

2021-11-11 09:44 UTC, psychocoderHPC commented
I think the CI issue is this: https://gitlab.com/hzdr/crp/alpaka/-/jobs/1769570585#L3295

2021-11-11 09:51 UTC, psychocoderHPC commented
I assume the CI issue is coming from testing 8bit and 16bit atomics with OpenAcc. @jkelling are 8 and 16bit atomics with OpenAcc supported?

2021-11-11 16:49 UTC, jkelling commented
> I assume the CI issue is coming from testing 8bit and 16bit atomics with OpenAcc. @jkelling are 8 and 16bit atomics with OpenAcc supported?

Technically, the standard does not define what data types atomics can work on, only which operations are supported. So, whatever the target supports is supported.

NVIDA GPUs do *not* support them, hence CUDA does not, hence NVHPC targeting nvptx does not. This is why https://github.com/alpaka-group/alpaka/commit/731e80d0ff3ba7ffea3985745639d4e4e5153d4b disabled these tests. This PR should apply the same exclusion mechanism established herein for CUDA on OpenACC and OpenMP5 (unfortunately we do not have a GPU test for this yet, but this would also fail for HSA).

2021-11-11 17:54 UTC, jkelling commented
> ```
> NVC++-S-0155-Invalid atomic capture.  (/builds/hzdr/crp/alpaka/test/unit/atomic/src/AtomicTest.cpp: 50)
> [...]
>```

Note, that there is a bug in NVHPC which always prints the main source file there. The line number actually refers to [AtomicOaccBuiltIn.hpp:50](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/atomic/AtomicOaccBuiltIn.hpp#L50), which is an atomic capture. The reason for the error is the 8 or 16 bit datatype.

I am actually a surprised about the two errors in the NVHPC x86 test:
```
NVC++-S-0155-Invalid atomic capture.  (/home/runner/work/alpaka/alpaka/test/unit/atomic/src/AtomicTest.cpp: 46)
NVC++-S-0155-Invalid atomic capture.  (/home/runner/work/alpaka/alpaka/test/unit/atomic/src/AtomicTest.cpp: 52)
```
For one, these passed for me locally with 8 and 16 bit enabled. The other thing is that [AtomicOaccBuiltIn.hpp:46](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/atomic/AtomicOaccBuiltIn.hpp#L46) would point to the directive itself, while the nvptx errors always point to the end of the block. Could be, that it refers to a different file. The other one could mean [AtomicOaccExtended.hpp:50](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/atomic/AtomicOaccExtended.hpp#L50). Let us see if these go away too when 8 and 16 bit is disable for OpenACC.

2021-11-19 16:05 UTC, bernhardmgruber commented on test/unit/atomic/src/AtomicTest.cpp
> +    std::enable_if_t<sizeof(T) <= 2> // disable 8-bit and 16-bit tests
```suggestion
    std::enable_if_t<sizeof(T) <= 2>> // disable 8-bit and 16-bit tests
```
You miss an angle bracket here.

2021-11-19 16:11 UTC, tonydp03 commented on test/unit/atomic/src/AtomicTest.cpp
> +    std::enable_if_t<sizeof(T) <= 2> // disable 8-bit and 16-bit tests
Right, commit fixed.

2021-11-22 19:25 UTC, BenjaminW3 approved these changes

2021-11-22 22:47 UTC, bernhardmgruber approved these changes

2021-11-22 22:47 UTC, merged