Wrapper adding operator[] to Cuda vector types
alpaka-group/alpaka pull request #1435
Opened 2021-10-28 12:26 UTC by sliwowitz

This wrapper add `operator[]` to CUDA vector types such as `int4`, `float3` etc. It is a user convenience for the API of the vector variants of the _Philox_ random generator. In a perfect world, these would return a `std::array`. Unfortunately many older `nvcc`s do not support `std::array`s in device code. Their vector types are a good match for the _Philox_ generator, but they're structs with members `.x`, `.y`, etc. This syntax doesn't make much sense for a result of a random number generator, thus this wrapper.

The limitation is that it does not provide all possible type-size combination. If more are needed, they have to be manually added as new `struct CudaVectorArrayTypeTraits<T, N>` specializations. I don't know how to generate these automatically without resorting to preprocessor macro black magic, and given the wrappers will hopefully soon become obsolete, I included only `int`, `unsigned`, `float` and `double` in sizes `1` to `4`.

2021-10-28 12:41 UTC, bernhardmgruber requested changes

2021-10-28 12:41 UTC, bernhardmgruber commented on test/unit/meta/src/IsArrayOrVectorTest.cpp
> +    static_assert(isArrayOrVectorStdArray, "alpaka::meta::IsArrayOrVector failed!");
```suggestion
    STATIC_REQUIRE(alpaka::meta::IsArrayOrVector<std::array<int, 10>>::value);
```
Catch2 can do that for you. Please apply in other places as well.

2021-10-28 12:41 UTC, bernhardmgruber commented on include/alpaka/meta/IsArrayOrVector.hpp
> +        struct IsArrayOrVector : std::false_type
I don't understand the semantic and use of that trait. Why only vector or array? What about `std::deque`? Is this supposed to be a concept? Would `llama::Array` fulfill that? What decisions are you going to take based on this information?

2021-10-28 12:41 UTC, bernhardmgruber commented on include/alpaka/meta/CudaVectorArrayWrapper.hpp
> +        };
```suggestion
        struct CudaVectorArrayWrapper;
```

2021-10-28 12:41 UTC, bernhardmgruber commented on include/alpaka/meta/CudaVectorArrayWrapper.hpp
> +            };
```suggestion
            struct CudaVectorArrayTypeTraits;
```

2021-10-28 12:41 UTC, bernhardmgruber commented on include/alpaka/meta/CudaVectorArrayWrapper.hpp
> +            }
Why can't we make this `constexpr` before C++17?

2021-10-28 12:42 UTC, bernhardmgruber commented
Please rebase this PR on the recent develop!

2021-10-28 12:46 UTC, sliwowitz commented on include/alpaka/meta/CudaVectorArrayWrapper.hpp
> +            }
Because *nvcc 9* will then fail with `qualifiers dropped in binding reference of type "unsigned int &" to initializer of type "const unsigned int"` when you do e.g. `unsigned x = myVector[2]`. The newer compiler I tried will accept the `constexpr` even in C++14 mode, but there's those infinite other combinatins in the CI. I was looking for anything useful on that matter and found out that GNU STL libstdc++ uses this exact trick in their `std::array` implementation which seemed good enough for me.

2021-10-28 12:46 UTC, sliwowitz commented on test/unit/meta/src/IsArrayOrVectorTest.cpp
> +    static_assert(isArrayOrVectorStdArray, "alpaka::meta::IsArrayOrVector failed!");
Didn't know that. I used to work with Boost.Test so Catch2 is new to me. Thanks!

2021-10-28 12:50 UTC, sliwowitz commented on include/alpaka/meta/IsArrayOrVector.hpp
> +        struct IsArrayOrVector : std::false_type
I use it to select a correct scalar/vector implementation of distributions - something like `UniformReal<PRNG_Result>` where `PRNG_Result` is usually a scalar, but could be a vector. Thinking about it, the concept could probably be satisfied by any collection that provides `operator[]`

2021-10-28 12:59 UTC, sliwowitz commented on include/alpaka/meta/CudaVectorArrayWrapper.hpp
> +        };
done

2021-10-28 13:00 UTC, sliwowitz commented on include/alpaka/meta/CudaVectorArrayWrapper.hpp
> +            };
done

2021-10-28 13:13 UTC, sliwowitz commented
> Please rebase this PR on the recent develop!

done

2021-10-28 13:40 UTC, bernhardmgruber commented on include/alpaka/meta/IsArrayOrVector.hpp
> +        struct IsArrayOrVector : std::false_type
I conjectured that you are requiring `operator[]` and thus your concept should be called something like `Subscriptable`. Then than you could use SFINAE to check it. Something like:
```c++
template <typename T, typename SFINAE = void>
struct Subscriptable : std::false_type {};

template <typename T>
struct Subscriptable<T, std::void_t<decltype(std::declval<T>()[0])> > : std::true_type {};
```

2021-10-28 13:44 UTC, bernhardmgruber commented on include/alpaka/meta/CudaVectorArrayWrapper.hpp
> +            }
Ahh, you might be right here. There was a time `constexpr` on a member function implied `const`, but I thought that changed from C++11 to C++14? Might be another nvcc bug.

2021-10-28 13:55 UTC, sliwowitz commented on include/alpaka/meta/CudaVectorArrayWrapper.hpp
> +            }
Yes. My guess would be a *nvcc* bug as well. But like I said, GNU STL's `std::array` does the same thing to their `operator[]` so I think it should be ok.

2021-10-28 13:57 UTC, sliwowitz commented on include/alpaka/meta/CudaVectorArrayWrapper.hpp
> +            }
Same in LLVM's `libcxx` https://github.com/llvm-mirror/libcxx/blob/78d6a7767ed57b50122a161b91f59f19c9bd0d19/include/array#L191

2021-10-28 16:46 UTC, sliwowitz commented on include/alpaka/meta/IsArrayOrVector.hpp
> +        struct IsArrayOrVector : std::false_type
I'm not sure about this because that would also accept a plain pointer like `float* x` and call the vector distribution on that which is probably not what was intended. I'm leaning to dropping this altogether, and instead requiring something like `T::size` because the distribution class needs to know the size of the vector anyway. This would not work on plain arrays though, but that's non-standard usage so let's say if someone really wants to put their custom array into our distributions, they have to wrap it in something like `std::array` first.

2021-10-28 16:54 UTC, bernhardmgruber commented on include/alpaka/meta/IsArrayOrVector.hpp
> +        struct IsArrayOrVector : std::false_type
You said you only need `operator[]`. Now you need a size as well :D

Anyway, then I let you figure out what you need.

2021-10-28 16:55 UTC, bernhardmgruber submitted a review, later dismissed

2021-10-28 17:01 UTC, sliwowitz commented on include/alpaka/meta/IsArrayOrVector.hpp
> +        struct IsArrayOrVector : std::false_type
I think this discussion would better fit the in the Philox PR where this stuff is actually used. I'll remove the two files form here, and solve it there after the CI doom subsides :-)

2021-11-01 17:33 UTC, bernhardmgruber approved these changes

2021-11-01 17:56 UTC, merged