Add ALPAKA_RELOCATABLE_DEVICE_CODE option
alpaka-group/alpaka pull request #1467
Opened 2021-11-15 13:12 UTC by j-stephan

Fixes #1292. Needs to be backported to 0.8 after merging.

2021-11-18 11:59 UTC, psychocoderHPC commented
@SimeonEhrig Could you please test this feature when you are back?

2021-11-18 12:02 UTC, psychocoderHPC commented on cmake/alpakaCommon.cmake
> +                if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 13.0)
Is this the workaround for https://github.com/alpaka-group/alpaka/issues/1292#issuecomment-823097652?

2021-11-18 12:07 UTC, psychocoderHPC requested changes, later dismissed

2021-11-18 12:07 UTC, psychocoderHPC commented on cmake/alpakaCommon.cmake
> +            else()
`elseif(ALPAKA_RELOCATABLE_DEVICE_CODE STREQUAL OFF)`

Alpaka is keeping always the default except we explicitly disable or enable such an option.

2021-11-18 12:07 UTC, psychocoderHPC commented on cmake/alpakaCommon.cmake
> +        else()
should be `elseif(ALPAKA_RELOCATABLE_DEVICE_CODE STREQUAL OFF)`

2021-11-18 12:07 UTC, psychocoderHPC commented on cmake/alpakaCommon.cmake
> +            else()
should be `elseif(ALPAKA_RELOCATABLE_DEVICE_CODE STREQUAL OFF)`

2021-11-18 12:07 UTC, psychocoderHPC commented on cmake/alpakaCommon.cmake
> +alpaka_compiler_option(RELOCATABLE_DEVICE_CODE "Enable relocatable device code for CUDA and HIP GPUs" OFF)
should be `DEFAULT` and not `OFF`. We keep if possible the compiler default and let the user choose an explicit behavior.

2021-12-02 15:34 UTC, SimeonEhrig commented
> @SimeonEhrig Could you please test this feature when you are back?

Is does not work. I modified the hello world example and added a `ALPAKA_STATIC_ACC_MEM_CONSTANT` variable, which lives in another TU. 

modified CMakeLists.txt
```diff
diff --git a/example/helloWorld/CMakeLists.txt b/example/helloWorld/CMakeLists.txt
index d29facbe42..89ddccf015 100644
--- a/example/helloWorld/CMakeLists.txt
+++ b/example/helloWorld/CMakeLists.txt
@@ -50,7 +50,8 @@ endif()
 
 alpaka_add_executable(
     ${_TARGET_NAME}
-    src/helloWorld.cpp)
+    src/helloWorld.cpp
+    src/global.cpp)
 target_link_libraries(
     ${_TARGET_NAME}
     PUBLIC alpaka::alpaka)
```

modified helloWorld.cpp
```diff
diff --git a/example/helloWorld/src/helloWorld.cpp b/example/helloWorld/src/helloWorld.cpp
index e0a37d18dd..f32df50acf 100644
--- a/example/helloWorld/src/helloWorld.cpp
+++ b/example/helloWorld/src/helloWorld.cpp
@@ -20,6 +20,8 @@
 
 #include <iostream>
 
+#include "global.hpp"
+
 //! Hello World Kernel
 //!
 //! Prints "[x, y, z][gtid] Hello World" where tid is the global thread number.
@@ -52,11 +54,12 @@ struct HelloWorldKernel
         // Mind, that alpaka uses the mathematical index
         // order [z][y][x] where the last index is the fast one.
         printf(
-            "[z:%u, y:%u, x:%u][linear:%u] Hello World\n",
+            "[z:%u, y:%u, x:%u][linear:%u] The anwser %i\n",
             static_cast<unsigned>(globalThreadIdx[0u]),
             static_cast<unsigned>(globalThreadIdx[1u]),
             static_cast<unsigned>(globalThreadIdx[2u]),
-            static_cast<unsigned>(linearizedGlobalThreadIdx[0u]));
+            static_cast<unsigned>(linearizedGlobalThreadIdx[0u]),
+              constant);
     }
 };
```

global.hpp
```cpp
#pragma once

#include <alpaka/alpaka.hpp>

extern ALPAKA_STATIC_ACC_MEM_CONSTANT int constant;
```

global.cpp
```cpp
#include "global.hpp"

ALPAKA_STATIC_ACC_MEM_CONSTANT int constant = 42;
```

compiler output:
```bash
$ cmake --build . -t helloWorld -v
[1/3] /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/c++ -DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED -DALPAKA_ACC_GPU_CUDA_ENABLED -DALPAKA_BLOCK_SHARED_DYN_MEMBER_ALLOC_KIB=47 -DALPAKA_DEBUG=0 -DALPAKA_DEBUG_OFFLOAD_ASSUME_HOST -DALPAKA_OFFLOAD_MAX_BLOCK_SIZE=256 -DBOOST_ALL_NO_LIB -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/targets/x86_64-linux/include -isystem=../include -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/boost-1.74.0-lqyr7ou7iafiwvq5fb6ipp62o6l2gqlf/include -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/include --generate-code=arch=compute_52,code=[compute_52,sm_52] --expt-extended-lambda --expt-relaxed-constexpr -rdc=true -Xcudafe=--display_error_number -Xcudafe=--diag_suppress=esa_on_defaulted_function_ignored -Xcompiler -pthread -std=c++14 -MD -MT example/helloWorld/CMakeFiles/helloWorld.dir/src/global.cpp.o -MF example/helloWorld/CMakeFiles/helloWorld.dir/src/global.cpp.o.d -x cu -c ../example/helloWorld/src/global.cpp -o example/helloWorld/CMakeFiles/helloWorld.dir/src/global.cpp.o
[2/3] /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/c++ -DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED -DALPAKA_ACC_GPU_CUDA_ENABLED -DALPAKA_BLOCK_SHARED_DYN_MEMBER_ALLOC_KIB=47 -DALPAKA_DEBUG=0 -DALPAKA_DEBUG_OFFLOAD_ASSUME_HOST -DALPAKA_OFFLOAD_MAX_BLOCK_SIZE=256 -DBOOST_ALL_NO_LIB -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/targets/x86_64-linux/include -isystem=../include -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/boost-1.74.0-lqyr7ou7iafiwvq5fb6ipp62o6l2gqlf/include -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/include --generate-code=arch=compute_52,code=[compute_52,sm_52] --expt-extended-lambda --expt-relaxed-constexpr -rdc=true -Xcudafe=--display_error_number -Xcudafe=--diag_suppress=esa_on_defaulted_function_ignored -Xcompiler -pthread -std=c++14 -MD -MT example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld.cpp.o -MF example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld.cpp.o.d -x cu -c ../example/helloWorld/src/helloWorld.cpp -o example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld.cpp.o
[3/3] : && /usr/bin/c++  example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld.cpp.o example/helloWorld/CMakeFiles/helloWorld.dir/src/global.cpp.o -o example/helloWorld/helloWorld  -pthread  /usr/lib/x86_64-linux-gnu/librt.so  /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/lib64/libcudart.so  -lcudadevrt  -lcudart_static  -lrt  -lpthread  -ldl -L"/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/targets/x86_64-linux/lib/stubs" -L"/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/targets/x86_64-linux/lib" && :
FAILED: example/helloWorld/helloWorld 
: && /usr/bin/c++  example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld.cpp.o example/helloWorld/CMakeFiles/helloWorld.dir/src/global.cpp.o -o example/helloWorld/helloWorld  -pthread  /usr/lib/x86_64-linux-gnu/librt.so  /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/lib64/libcudart.so  -lcudadevrt  -lcudart_static  -lrt  -lpthread  -ldl -L"/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/targets/x86_64-linux/lib/stubs" -L"/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/targets/x86_64-linux/lib" && :
/usr/bin/ld: example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld.cpp.o: in function `__sti____cudaRegisterAll()':
tmpxft_00145b42_00000000-6_helloWorld.cudafe1.cpp:(.text+0x6be): undefined reference to `__cudaRegisterLinkedBinary_45_tmpxft_00145b42_00000000_7_helloWorld_cpp1_ii_main'
/usr/bin/ld: example/helloWorld/CMakeFiles/helloWorld.dir/src/global.cpp.o: in function `__sti____cudaRegisterAll()':
tmpxft_00145b43_00000000-6_global.cudafe1.cpp:(.text+0x37b): undefined reference to `__cudaRegisterLinkedBinary_41_tmpxft_00145b43_00000000_7_global_cpp1_ii_constant'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

2021-12-02 19:09 UTC, j-stephan commented
While addressing the requested changes I noticed that full support for clang-cuda and `CUDA_SEPARABLE_COMPILATION` is only available in CMake 3.19. I can either do evil things and try to override the linker somehow or we can just upgrade to a more recent CMake variant. I'll address the latter in a separate PR.

2021-12-02 20:33 UTC, j-stephan commented
I'm considering to shift this PR to 0.9 because of #1509. @SimeonEhrig @psychocoderHPC Do we require this feature for 0.8?

2021-12-06 07:47 UTC, SimeonEhrig commented
> I'm considering to shift this PR to 0.9 because of #1509. @SimeonEhrig @psychocoderHPC Do we require this feature for 0.8?

No, the ePIE code uses only constant memory inside a single TU. I can also use dev versions, than a restructure of the ePIE project.

2022-01-19 15:33 UTC, j-stephan commented
Putting on hold until #1509 has been adressed (or at least CMake 3.19 is available by default).

2022-04-13 06:24 UTC, fwyzard commented
> ```shell
> [1/3] /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/c++ -DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED -DALPAKA_ACC_GPU_CUDA_ENABLED -DALPAKA_BLOCK_SHARED_DYN_MEMBER_ALLOC_KIB=47 -DALPAKA_DEBUG=0 -DALPAKA_DEBUG_OFFLOAD_ASSUME_HOST -DALPAKA_OFFLOAD_MAX_BLOCK_SIZE=256 -DBOOST_ALL_NO_LIB -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/targets/x86_64-linux/include -isystem=../include -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/boost-1.74.0-lqyr7ou7iafiwvq5fb6ipp62o6l2gqlf/include -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/include --generate-code=arch=compute_52,code=[compute_52,sm_52] --expt-extended-lambda --expt-relaxed-constexpr -rdc=true -Xcudafe=--display_error_number -Xcudafe=--diag_suppress=esa_on_defaulted_function_ignored -Xcompiler -pthread -std=c++14 -MD -MT example/helloWorld/CMakeFiles/helloWorld.dir/src/global.cpp.o -MF example/helloWorld/CMakeFiles/helloWorld.dir/src/global.cpp.o.d -x cu -c ../example/helloWorld/src/global.cpp -o example/helloWorld/CMakeFiles/helloWorld.dir/src/global.cpp.o
> [2/3] /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/c++ -DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED -DALPAKA_ACC_GPU_CUDA_ENABLED -DALPAKA_BLOCK_SHARED_DYN_MEMBER_ALLOC_KIB=47 -DALPAKA_DEBUG=0 -DALPAKA_DEBUG_OFFLOAD_ASSUME_HOST -DALPAKA_OFFLOAD_MAX_BLOCK_SIZE=256 -DBOOST_ALL_NO_LIB -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/targets/x86_64-linux/include -isystem=../include -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/boost-1.74.0-lqyr7ou7iafiwvq5fb6ipp62o6l2gqlf/include -isystem=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/include --generate-code=arch=compute_52,code=[compute_52,sm_52] --expt-extended-lambda --expt-relaxed-constexpr -rdc=true -Xcudafe=--display_error_number -Xcudafe=--diag_suppress=esa_on_defaulted_function_ignored -Xcompiler -pthread -std=c++14 -MD -MT example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld.cpp.o -MF example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld.cpp.o.d -x cu -c ../example/helloWorld/src/helloWorld.cpp -o example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld.cpp.o
> [3/3] : && /usr/bin/c++  example/helloWorld/CMakeFiles/helloWorld.dir/src/helloWorld.cpp.o example/helloWorld/CMakeFiles/helloWorld.dir/src/global.cpp.o -o example/helloWorld/helloWorld  -pthread  /usr/lib/x86_64-linux-gnu/librt.so  /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/lib64/libcudart.so  -lcudadevrt  -lcudart_static  -lrt  -lpthread  -ldl -L"/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/targets/x86_64-linux/lib/stubs" -L"/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-11.0.2-mtxiuzc35ykbmjk4fnpmhwnjbgquvcv5/targets/x86_64-linux/lib" && :
> FAILED: example/helloWorld/helloWorld 
> ```

To me it looks like it is missing the "device link" step:
  - `helloWorld` should be linked by `nvcc --link` instead of `c++`
  - or, first `global.cpp.o` and `helloWorld.cpp.o` should be device-linked with
    ```
    nvcc -dlink global.cpp.o helloWorld.cpp.o -o helloWorld.dlink.o
    ```
    and then the resulting object file should be linked into `helloWorld` along with the rest
  - or, the same could be done with `nvlink` and `fatbinary`
    (this is a bit more verbose and complicated, but can be useful in case one is compiling with `clang -cuda` instead of `nvcc` - check what `nvcc -dlink -verbose` does for you...)

2023-02-15 10:28 UTC, j-stephan commented
Looks like these flags are ICEing the ROCm compiler. Let us wait for #1915 to be merged to see if this was maybe fixed in ROCm 5.4.

2023-02-17 10:27 UTC, j-stephan commented on cmake/alpakaCommon.cmake
> +
@psychocoderHPC Do you know whether there are any missing options here? All ROCm CI Runners are failing with an ICE sooner or later.

2023-08-10 11:23 UTC, j-stephan commented
@psychocoderHPC @SimeonEhrig This is now ready for review and merging. Please have a look once you guys are back from your vacation(s).

2023-08-10 11:25 UTC, j-stephan commented on cmake/alpakaCommon.cmake
> -    alpaka_set_compiler_options(DEVICE target alpaka "-fsycl-unnamed-lambda") # Compiler default but made explicit here
This was removed because it is already set above in line 657. Looks like a faulty merge that we have overlooked previously.

2023-08-21 14:45 UTC, SimeonEhrig commented
@j-stephan My example is working. Please update the documentation: https://github.com/alpaka-group/alpaka/blob/79c3113a989f78757ac7ae3ca3513f4344f3a180/docs/source/advanced/cmake.rst?plain=1#L200

2023-08-21 15:43 UTC, SimeonEhrig commented
Update, I tested my [example](https://github.com/alpaka-group/alpaka/pull/1467#issuecomment-984738706) also on hip. So in a short test, following configurations are working:

- CUDA 12.1 on a Nvidia A30
- HIP 5.5 on a Radeon RX 6700XT

2023-08-21 15:43 UTC, SimeonEhrig approved these changes

2023-08-22 06:13 UTC, merged