Add clang-13 to CI
alpaka-group/alpaka pull request #1485
Opened 2021-11-30 07:23 UTC by bernhardmgruber

Fixes #1476

2021-11-30 08:44 UTC, bernhardmgruber commented
Looks like `clang-13` is not available on Ubuntu 20.04 from the standard repositories.

2021-11-30 09:00 UTC, SimeonEhrig commented
At the moment, I working on this subject for the GitLab Container. You need to add the following ppa's:
```
deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main
deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main
```

2021-12-03 14:26 UTC, j-stephan approved these changes, later dismissed

2021-12-04 12:47 UTC, bernhardmgruber commented
Okay, we finally hit the Catch2 bug, @j-stephan reported a while ago: https://github.com/catchorg/Catch2/issues/578
```c++
/home/runner/work/alpaka/alpaka/test/integ/mandelbrot/src/mandelbrot.cpp:259:1: error: identifier '____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____F_U_N_C____0' is reserved because it starts with '__' [-Werror,-Wreserved-identifier]
```

2021-12-16 13:57 UTC, bernhardmgruber commented
Catch2 issue is fixed on their development branch, includes in this PR.

2021-12-16 15:54 UTC, j-stephan commented
Also fixes #1388.

2021-12-17 07:00 UTC, psychocoderHPC requested changes
unfortunately, you missed updating README.md :-(

Please rebase after you updated the file.

2021-12-17 07:37 UTC, psychocoderHPC approved these changes

2021-12-17 07:37 UTC, psychocoderHPC commented
This PR passed already the CI but a change in the README was required, therefore I will merge it before the CI is passing.

2021-12-17 07:37 UTC, merged