Add nvcc 11.5 to CI
alpaka-group/alpaka pull request #1486
Opened 2021-11-30 07:29 UTC by bernhardmgruber

Fixes #1475

2021-11-30 14:14 UTC, psychocoderHPC commented
Why do we not add it to the HZDR CI. We are working on removing such jobs from the workflows, IMO this is doubling the work.

2021-11-30 14:17 UTC, bernhardmgruber commented
> Why do we not add it to the HZDR CI. We are working on removing such jobs from the workflows, IMO this is doubling the work.

Because I have less experience with the GitLab CI and nobody else did it. But please, go ahead and add the GitLab CI jobs! I can close this PR when yours is ready.

2021-11-30 14:18 UTC, psychocoderHPC commented
It is equal to adding it to git workflows. The difference is that it is not on one line.

https://github.com/alpaka-group/alpaka/blob/ac1ccf380d4208fbff8e5c592f649c569a9a308a/script/gitlabci/job_cuda.yml#L2-L12

Best is to have a base job file per cuda version and than add it to .gitlab.yml but you removed it in one of the last PRs.

2021-12-01 08:13 UTC, psychocoderHPC commented
@SimeonEhrig mentioned yesterday that NVIDIA is currently not providing CUDA 11.5 docker containers because they have issues building them. The HZDR CI is using CUDA docker container as a base to avoid driver issue I got with normal ubuntu container when installing CUDA via apt only.
So we will merge this one before #1491 and I will work on fixing the dependency to NVIDIA docker container in the HZDR CI if NVIDIA is not providing docker container before I can work on this topic.

2021-12-01 08:13 UTC, psychocoderHPC requested changes

2021-12-01 08:13 UTC, psychocoderHPC commented on .github/workflows/ci.yml
> +        ## CUDA 11.5
Could you please update the build matrix in README.md .

2021-12-01 08:32 UTC, SimeonEhrig commented
> @SimeonEhrig mentioned yesterday that NVIDIA is currently not providing CUDA 11.5 docker containers because they have issues building them. The HZDR CI is using CUDA docker container as a base to avoid driver issue I got with normal ubuntu container when installing CUDA via apt only. So we will merge this one before #1491 and I will work on fixing the dependency to NVIDIA docker container in the HZDR CI if NVIDIA is not providing docker container before I can work on this topic.

https://gitlab.com/nvidia/container-images/cuda/-/issues/142

2021-12-01 09:56 UTC, psychocoderHPC submitted a review, later dismissed

2021-12-03 07:45 UTC, psychocoderHPC approved these changes

2021-12-03 07:45 UTC, merged