Extend a queue's lifetime until async memory operations are complete
alpaka-group/alpaka pull request #1514
Opened 2021-12-07 10:51 UTC by fwyzard

2021-12-07 10:52 UTC, fwyzard commented
This is mostly to test if extending the queue's lifetime would be enough to guarantee that the memory is properly freed.

2021-12-07 11:23 UTC, bernhardmgruber submitted a review, later dismissed

2021-12-07 11:23 UTC, bernhardmgruber commented on test/unit/mem/buf/src/BufTest.cpp
> +    // and extend the lifetime of the queue untul all memory operations have completed.
```suggestion
    // and extend the lifetime of the queue until all memory operations have completed.
```

2021-12-07 11:23 UTC, bernhardmgruber commented on test/unit/mem/buf/src/BufTest.cpp
> +    // and extend the lifetime of the queue untul all memory operations have completed.
```suggestion
    // and extend the lifetime of the queue until all memory operations have completed.
```

2021-12-07 15:11 UTC, j-stephan requested changes
Thanks. Please address Bernhard's comment and we're good to merge.

2021-12-08 08:58 UTC, fwyzard commented
I've tested that the change does not have any measurable impact on the performance of our standalone application.

2021-12-08 09:25 UTC, bernhardmgruber approved these changes

2021-12-08 16:52 UTC, bernhardmgruber approved these changes

2021-12-08 16:52 UTC, bernhardmgruber commented
@j-stephan please approve and merge!

2021-12-08 18:31 UTC, j-stephan approved these changes

2021-12-08 18:31 UTC, merged