run nvidia-smi in all CUDA CI jobs
alpaka-group/alpaka pull request #1589
Opened 2022-02-07 15:00 UTC by SimeonEhrig

During repairing the CI, I recognized that `nvidia-smi` is not executed in regular CUDA jobs.

2022-02-07 16:03 UTC, psychocoderHPC submitted a review, later dismissed

2022-02-10 18:06 UTC, j-stephan approved these changes

2022-02-10 18:07 UTC, j-stephan requested changes
Locking this until @psychocoderHPC has reviewed the PR. Anyone else: Please don't merge yet.

2022-02-14 12:44 UTC, j-stephan approved these changes

2022-02-14 12:44 UTC, merged