Renamed "traits" namespace to "trait"
alpaka-group/alpaka pull request #1651
Opened 2022-03-16 16:46 UTC by tonydp03

Following the issue #179 , the Alpaka namespace "traits" was renamed to "trait" in all its occurrencies. However, are we sure we want to keep the namespace and not removing it entirely to simplify the code, as @bernhardmgruber suggested?

2022-03-17 06:53 UTC, psychocoderHPC commented
I am against removing the `trait` namepsace. The namespace is separating the free functions the user is touching from the implementations alpaka developer or experts are providing. see https://alpaka-group.github.io/alpaka/namespaces.html

2022-03-17 13:50 UTC, bernhardmgruber approved these changes, later dismissed
I did not check every file, but I think trusting the CI is fine in this case.

2022-03-18 09:46 UTC, bernhardmgruber commented
The commit was made with @tonydp03 as author. @psychocoderHPC do you insist on commiting under the Tools author? And @j-stephan do you want @tonydp03 to update all the copyright headers? I don't care much about both of them.

2022-03-18 09:53 UTC, psychocoderHPC requested changes
@bernhardmgruber mentioned it please commit your changes with

```
GIT_AUTHOR_NAME="Tools" GIT_AUTHOR_EMAIL="alpaka@hzdr.de" git commit ...
```

This PR is mostly processed with search and replace. We try to submit automated changes under an generic user.

2022-03-18 09:59 UTC, j-stephan commented
If we have the tools author I don't think we need to update the copyright header.

2022-03-18 10:02 UTC, tonydp03 commented
I'll change the headers, rebase, and squash the new commit with the previous one under the Tools author.

2022-03-18 14:24 UTC, bernhardmgruber approved these changes

2022-03-20 22:26 UTC, bernhardmgruber approved these changes

2022-03-21 09:41 UTC, psychocoderHPC approved these changes

2022-03-21 09:41 UTC, merged