Accumulate memcpy/memset static_asserts
alpaka-group/alpaka pull request #1748
Opened 2022-06-22 09:55 UTC by bernhardmgruber

2022-06-22 13:00 UTC, bernhardmgruber commented on include/alpaka/mem/buf/cpu/Copy.hpp
> -                "The destination view and the input TDim are required to have the same dimensionality!");
Asserts of this sort are not replicated in the traits, because we literally pass `Dim<TViewDst>` as template argument for the `TDim` parameter.

2022-06-23 09:09 UTC, j-stephan commented
Please set the appropriate labels and project!

2022-06-23 09:11 UTC, bernhardmgruber commented
Done!

2022-06-23 09:15 UTC, j-stephan requested changes
Thanks! Just some typos:

2022-06-23 09:15 UTC, j-stephan commented on include/alpaka/mem/view/Traits.hpp
> +            "The view and the extent must have compatible idx type!");
```suggestion
            "The view and the extent must have compatible Idx types!");
```

2022-06-23 09:15 UTC, j-stephan commented on include/alpaka/mem/view/Traits.hpp
> +            "The source view and the extent are required to have compatible idx type!");
Also here.

2022-06-23 15:43 UTC, j-stephan approved these changes

2022-06-23 17:30 UTC, merged