Fix missing `final` keyword for accelerator inheritance
alpaka-group/alpaka pull request #1816
Opened 2022-10-20 10:19 UTC by psychocoderHPC

Most of the accelerators a marked with the keyword `final`, therefore it is not possible to inherit from these accelerators.

This PR adds the final keyword to all accelerators to avoid different behavior depending on the accelerator.

2022-10-20 10:22 UTC, psychocoderHPC commented
In general, I do not know why we forbid that we can inherit from an accelerator. As I can see all acc's can be copied too, does anyone has an idea why it is how it is?

2022-10-21 08:17 UTC, j-stephan requested changes

2022-10-21 08:17 UTC, j-stephan commented on include/alpaka/acc/AccGenericSycl.hpp
> +    class AccGenericSycl final
This must not be `final` because it is the abstract base class for the concrete SYCL implementations.

2022-10-21 08:24 UTC, j-stephan commented
My guess is that we don't want users to derive from our `Acc`s and then override parent methods. This is legal in C++ but might have bad consequences in CUDA and probably the other back-ends, too. But this is something I only can assume, maybe @BenjaminW3 still remembers.

If we cannot establish a reason for keeping them `final` the keywords should be removed IMO. Maybe there was a good reason in the past that is no longer valid.

2022-10-21 16:09 UTC, BenjaminW3 commented
I also do not remember why they are final 🤷

2022-10-24 16:30 UTC, psychocoderHPC commented
The question why I am asking is that I am currently [refactoring PIConGPU/PMacc](https://github.com/ComputationalRadiationPhysics/picongpu/pull/4321) where we introduce our own context element.
Currently, I store within this PMacc context a reference to the alpaka ACC which is not nice at all.
If we would allow that I can inherit from an accelerator I could pass the PMacc context to any alpaka function and because of our alpaka concepts light, all should work nice.
So in general would like to get rid of the final keyword to extend the alpaka accelerator with user information.

PIConGPU lockstep kernel (our own programming model to handle CPU accelerators with thread restrictions for the block and GPU accelerators would than look like this.

```C++
PMACC_LOCKSTEP_KERNEL([]ALPAKA_FN_ACC(auto const& worker) -> void{
    // domain/elements size is 123
    auto forEach = pmacc::lockstep::makeForEach<123>(worker);
    forEach([&](uint32_t const idx){
      printf("Hello World element=%u worker=%u.\n", idx, worker.getWorkerIdx());
    });
})(5)();
```

2022-10-25 15:40 UTC, j-stephan commented
I won't oppose a PR removing `final` from our Accs. It doesn't seem that we have a good reason for keeping it around so feel free to un-finalize.

2022-11-25 15:31 UTC, psychocoderHPC commented
> I won't oppose a PR removing `final` from our Accs. It doesn't seem that we have a good reason for keeping it around so feel free to un-finalize.

Yes, I will remove the final `AccGenericSycl` as suggested because it is wrong there but all others should be there to avoid someone inheriting from the accelerator.
In a separate PR I will forbid the copy and move constructor to ensure that states e.g. for shared memory will not be invalidated.

2022-11-28 20:26 UTC, psychocoderHPC commented
ready to be merged

2022-11-29 10:50 UTC, SimeonEhrig approved these changes

2022-11-29 10:50 UTC, bernhardmgruber approved these changes

2022-11-30 19:10 UTC, psychocoderHPC commented
@j-stephan ping

2022-12-01 09:54 UTC, j-stephan approved these changes

2022-12-01 09:55 UTC, merged