Implement trait constants
alpaka-group/alpaka pull request #1818
Opened 2022-10-23 13:15 UTC by fwyzard

Implement the constpextr template variables
  - `alpaka::isAccelerator<T>`
  - `alpaka::isDevice<T>`
  - `alpaka::isPlatform<T`>
  - `alpaka::isQueue<T>`
that evaluate to `true` if the given type implements the corresponding concept.

2022-10-23 13:15 UTC, fwyzard commented
I've been using something similar to simplify the SFINAE checks in our code, I though they could be useful in general.

2022-10-26 11:17 UTC, fwyzard commented
Could anyone have a look at the XCode runners ?
I'm getting the error
```
CMake Error at cmake/alpakaCommon.cmake:391 (message):
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
  Optional alpaka dependency OpenMP could not be found!
-- Could NOT find OpenMP (missing: OpenMP_CXX_FOUND) 
Call Stack (most recent call first):
-- Configuring incomplete, errors occurred!
  CMakeLists.txt:88 (include)
```
which I think is unrelated to these changes.

2022-10-26 13:50 UTC, j-stephan commented
Hm, not sure what is going on there. According to the logs OpenMP is installed correctly. I'll look into it after ACAT if noone else picks it up until then.

2022-11-04 12:22 UTC, psychocoderHPC commented
I removed MACOSX from the required passing tests because nobody of us owns an MAC to test whats going on: see https://github.com/alpaka-group/alpaka/issues/1821

I restarted the failing windows CI job.

2022-11-07 14:39 UTC, fwyzard commented
Rebased, to re-trigger the tests

2023-01-09 08:29 UTC, fwyzard commented
Rebased on top of #1890 (merged).

2023-01-11 11:35 UTC, j-stephan requested changes

2023-01-11 11:35 UTC, j-stephan commented on include/alpaka/acc/Traits.hpp
> +#endif
These can be removed now, clang-6 is no longer in our support matrix.

2023-01-11 22:45 UTC, j-stephan approved these changes, later dismissed

2023-01-12 09:28 UTC, j-stephan commented
LGTM. Please rebase so the macOS CI update is pulled in. Just restarting the GitHub runners unfortunately didn't do the trick.

2023-01-13 12:32 UTC, j-stephan commented
Please rebase (again)... the CI should work again now. Sorry for the noise.

2023-01-16 08:17 UTC, fwyzard commented
eventually the CIs will pass...

2023-01-16 18:28 UTC, j-stephan approved these changes
Thanks!

2023-01-16 18:29 UTC, merged