remove bost 1.73 warning
alpaka-group/alpaka pull request #1849
Opened 2022-12-01 12:51 UTC by psychocoderHPC

alpaka requires boost 1.74.0+ therefore wrnings for the boost <1.73.0 can be removed.

2022-12-01 13:02 UTC, fwyzard commented
for those of us not using CMake, is there a `#warning` or `#error` somewhere else, if the version of Boost is too old ?

2022-12-03 23:48 UTC, bernhardmgruber approved these changes, later dismissed

2022-12-04 23:07 UTC, j-stephan commented
I think this was introduced by CMS to have a diagnostic outside of CMake. We should keep the warning until we have better diagnostics as part of the standalone headers.

2022-12-04 23:07 UTC, j-stephan requested changes
See above.

2022-12-07 19:17 UTC, psychocoderHPC commented
> I think this was introduced by CMS to have a diagnostic outside of CMake. We should keep the warning until we have better diagnostics as part of the standalone headers.

This warning has nothing todo with the minimum boost version we support. So this line should be removed.


> for those of us not using CMake, is there a #warning or #error somewhere else, if the version of Boost is too old ?

@fwyzard I think we do not reflect the requirements as `#warning` or `#error` in the code but we should do it if someone is using standalone headers. Never the less this issue is independent of the error I remove with this PR.

2022-12-07 19:20 UTC, psychocoderHPC commented
I opened an issue that the tasks to verify the boost version in the code base is not get lost https://github.com/alpaka-group/alpaka/issues/1856

2022-12-07 19:22 UTC, psychocoderHPC commented
I rebased the PR to re-trigger the CI

2022-12-07 19:42 UTC, fwyzard commented
> Never the less this issue is independent of the error I remove with this PR.

Agreed, and thanks for opening https://github.com/alpaka-group/alpaka/issues/1856.

2022-12-07 19:48 UTC, bernhardmgruber submitted a review, later dismissed

2022-12-08 10:16 UTC, j-stephan approved these changes, later dismissed

2022-12-08 10:17 UTC, j-stephan commented
Looks like the GitLab CI was never started. Can you trigger it again?

2022-12-09 10:20 UTC, psychocoderHPC commented
I restarted the CI.

2022-12-09 10:31 UTC, bernhardmgruber approved these changes

2022-12-09 12:32 UTC, j-stephan commented
> Agreed, and thanks for opening https://github.com/alpaka-group/alpaka/issues/1856.

FYI, this is now tracked in #1636.

2022-12-09 12:32 UTC, j-stephan approved these changes

2022-12-13 09:45 UTC, merged