Mark CATCH cmake variables as advanced
alpaka-group/alpaka pull request #1862
Opened 2022-12-09 14:17 UTC by bernhardmgruber

Fixes: #1758

2022-12-09 16:57 UTC, j-stephan requested changes

2022-12-09 16:57 UTC, j-stephan commented on thirdParty/CMakeLists.txt
> +    endforeach()
The indentation is wrong here.

2022-12-12 15:36 UTC, bernhardmgruber commented on thirdParty/CMakeLists.txt
> +    endforeach()
Would be great to have a clang-format for cmake!

2022-12-12 15:44 UTC, j-stephan approved these changes

2022-12-13 09:34 UTC, merged