Refactor ConcurrentExecPool
alpaka-group/alpaka pull request #2000
Opened 2023-07-04 17:24 UTC by bernhardmgruber

TODO:

- [ ] Merge #1998 first

2023-07-04 17:54 UTC, fwyzard commented
ooohhhh... 2000 !

2023-07-05 15:29 UTC, psychocoderHPC commented
@bernhardmgruber This PR can be rebased

2023-07-05 15:35 UTC, psychocoderHPC approved these changes

2023-07-05 15:36 UTC, psychocoderHPC requested changes

2023-07-05 15:36 UTC, psychocoderHPC commented on include/alpaka/core/ThreadPool.hpp
> +#include <vector>
`#inlcude <optional>` is missing

2023-07-05 15:44 UTC, bernhardmgruber commented on include/alpaka/core/ThreadPool.hpp
> +#include <vector>
Thx!

2023-07-06 08:35 UTC, psychocoderHPC approved these changes

2023-07-06 08:35 UTC, merged