extend inline macro documentation
alpaka-group/alpaka pull request #2091
Opened 2023-08-24 13:47 UTC by psychocoderHPC

The inline macro should be left of any keyword because depending of the alpaka backend std attribute specifiers will be used.

2023-08-24 13:49 UTC, psychocoderHPC commented on include/alpaka/core/Common.hpp
> +//! @code{.cpp}
Sry for sneaking in this change, I first commented by accident on this part and realized that only ALPAKAFN_INLINE is affected but would like to keep this change due to the correct usage of doxygen.

2023-08-24 14:06 UTC, j-stephan requested changes

2023-08-24 14:06 UTC, j-stephan commented on include/alpaka/core/Common.hpp
> +//! Macro should stay left hand side of keyword e.g. 'static', 'constexpr', 'explicit' or the return type.
```suggestion
//! The macro should stay on the left hand side of keywords, e.g. 'static', 'constexpr', 'explicit' or the return type).
```

2023-08-25 09:24 UTC, bernhardmgruber approved these changes

2023-08-25 10:14 UTC, j-stephan approved these changes

2023-08-25 10:14 UTC, merged