Fix tsan error: change memory randomization
alpaka-group/alpaka pull request #2250
Opened 2024-03-19 13:18 UTC by mehmetyusufoglu

Decrease mmap randomization to fix the tsan error `FATAL: ThreadSanitizer: unexpected memory mapping`

2024-03-19 14:43 UTC, psychocoderHPC commented
This looks like the similar issue: https://github.com/google/sanitizers/issues/1716

2024-03-19 14:48 UTC, psychocoderHPC commented
If I see it correctly the bug should be solved in llvm 17+ see https://github.com/llvm/llvm-project/commit/fb77ca05ffb4f8e666878f2f6718a9fb4d686839

2024-03-19 15:00 UTC, SimeonEhrig commented
> If I see it correctly the bug should be solved in llvm 17+ see [llvm/llvm-project@fb77ca0](https://github.com/llvm/llvm-project/commit/fb77ca05ffb4f8e666878f2f6718a9fb4d686839)

No, it does not solve the problem. I already tested it: https://github.com/alpaka-group/alpaka/pull/2249/commits/812035ea3733a8854501deec9454b7dda3652ffe

I think, this fixes another bug.

2024-03-19 15:08 UTC, mehmetyusufoglu commented
this is a workaround for linux OS. Tsan does not fail anymore.
`sudo sysctl vm.mmap_rnd_bits=28`

2024-03-19 15:10 UTC, SimeonEhrig requested changes

2024-03-19 15:10 UTC, SimeonEhrig commented on script/set.sh
> +sudo sysctl vm.mmap_rnd_bits=28
You was faster. I would also suggest it :-) It works.

Please guard it with:

```bash
if [ -n "$GITHUB_ACTIONS" ] && [ "$ALPAKA_CI_OS_NAME" = "Linux" ]; then
    sudo sysctl vm.mmap_rnd_bits=28
fi
```

An move it to `ci.sh`. `set.sh` is sourced many times and it's meaning is really executing the `set` command for the bash.

2024-03-19 16:23 UTC, psychocoderHPC approved these changes

2024-03-19 16:23 UTC, psychocoderHPC commented
@mehmetyusufoglu please update the description of this PR

2024-03-19 19:35 UTC, mehmetyusufoglu commented
> @mehmetyusufoglu please update the description of this PR

Done, thanks.

2024-03-20 06:54 UTC, SimeonEhrig approved these changes

2024-03-20 06:54 UTC, merged