Make all Examples use getValidWorkDivForKernel function
alpaka-group/alpaka pull request #2261
Opened 2024-05-01 22:35 UTC by mehmetyusufoglu

Replaces the `getValidWorkDiv` function with `getValidWorkDivForKernel` which take into account the kernel in calculating workdiv.

This PR will be merged after  https://github.com/alpaka-group/alpaka/pull/2251

2024-06-27 08:44 UTC, psychocoderHPC commented
Please rebase against the dev branch to pull https://github.com/alpaka-group/alpaka/pull/2293 and update this example too.

2024-07-05 08:53 UTC, psychocoderHPC commented
@mehmetyusufoglu the CI says, looks like a missing include

```
/builds/hzdr/crp/alpaka/example/convolution2D/src/convolution2D.cpp:308:30: error: use of undeclared identifier 'KernelBundle'
const auto &bundeledKernel = KernelBundle(convolutionKernel2D, alpaka::getPtrNative(bufInputAcc), alpaka::getPtrNative(outputDeviceMemory), matrixWidth, matrixHeight, alpaka::getPtrNative(bufFilterAcc), filterWidth, intputWidthAllocated, filterWidthAllocated); 
                             ^
/builds/hzdr/crp/alpaka/example/convolution2D/src/convolution2D.cpp:406:67: note: in instantiation of function template specialization 'example<alpaka::TagGpuCudaRt>' requested here
return alpaka::executeForEachAccTag([=](const auto &tag) { return example(tag); } ); 
                                                                  ^
/builds/hzdr/crp/alpaka/example/convolution2D/src/convolution2D.cpp:308:30: error: use of undeclared identifier 'KernelBundle'
const auto &bundeledKernel = KernelBundle(convolutionKernel2D, alpaka::getPtrNative(bufInputAcc), alpaka::getPtrNative(outputDeviceMemory), matrixWidth, matrixHeight, alpaka::getPtrNative(bufFilterAcc), filterWidth, intputWidthAllocated, filterWidthAllocated); 
                             ^
/builds/hzdr/crp/alpaka/example/convolution2D/src/convolution2D.cpp:406:67: note: in instantiation of function template specialization 'example<alpaka::TagCpuThreads>' requested here
return alpaka::executeForEachAccTag([=](const auto &tag) { return example(tag); } ); 
                                                                  ^
/builds/hzdr/crp/alpaka/example/convolution2D/src/convolution2D.cpp:308:30: error: use of undeclared identifier 'KernelBundle'
const auto &bundeledKernel = KernelBundle(convolutionKernel2D, alpaka::getPtrNative(bufInputAcc), alpaka::getPtrNative(outputDeviceMemory), matrixWidth, matrixHeight, alpaka::getPtrNative(bufFilterAcc), filterWidth, intputWidthAllocated, filterWidthAllocated); 
                             ^
/builds/hzdr/crp/alpaka/example/convolution2D/src/convolution2D.cpp:406:67: note: in instantiation of function template specialization 'example<alpaka::TagCpuSerial>' requested here
return alpaka::executeForEachAccTag([=](const auto &tag) { return example(tag); } ); 

```

2024-07-05 08:55 UTC, psychocoderHPC requested changes
please remove `getValidWorkdiv` a be sure all examples using the fixed version.

2024-07-22 07:34 UTC, psychocoderHPC commented
@mehmetyusufoglu  Please update the cheat sheet too! and check for other usages of `getValidWorkdiv(`

2024-07-22 08:31 UTC, mehmetyusufoglu commented
Ok doing now. Thanks

22 Tem 2024 Pzt 09:35 tarihinde René Widera ***@***.***> şunu
yazdı:

> @mehmetyusufoglu <https://github.com/mehmetyusufoglu> Please update the
> cheat sheet too! and check for other usages of getValidWorkdiv(
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alpaka-group/alpaka/pull/2261#issuecomment-2242285057>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUYXIJPUKK6SJP76UUMBW5LZNSY27AVCNFSM6AAAAABHCVEPYSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBSGI4DKMBVG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-24 08:02 UTC, psychocoderHPC approved these changes

2024-07-24 08:02 UTC, merged

2024-07-24 12:31 UTC, psychocoderHPC commented on include/alpaka/kernel/KernelBundle.hpp
> +        using ArgTuple = std::tuple<std::decay_t<TArgs>...>;
why do you removed `remove_restrict_t`?