fix and update SYCL targets
alpaka-group/alpaka pull request #2390
Opened 2024-09-18 15:37 UTC by AuroraPerego

Now all device targets are defined as 0, while the one(s) we are compiling for are defined as 1. Therefore `# if defined` cannot be used anymore.

I've added some new targets as well.

Note that there is probably a bug with NVIDIA targets, but we are not using them for now.

2024-09-18 16:07 UTC, fwyzard approved these changes

2024-09-18 21:11 UTC, fwyzard requested changes
I need to check some of the updates.

2024-09-19 07:26 UTC, fwyzard commented
@psychocoderHPC the error in `mathTest` ([link](https://gitlab.com/hzdr/crp/alpaka/-/jobs/7858709846#L3820), [attached log](https://github.com/user-attachments/files/17055196/job.log)) should be unrelated to this PR:
```
Randomness seeded to: 2485158815
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mathTest is a Catch2 v3.5.2 host application.
Run with -? for options
-------------------------------------------------------------------------------
mathOpsComplexFloat - TestAccFunctorTuplesComplex - 49
-------------------------------------------------------------------------------
/builds/hzdr/crp/alpaka/test/unit/math/src/mathComplexFloat.cpp:26
.............................................................................../builds/hzdr/crp/alpaka/test/unit/math/src/TestTemplate.hpp:145: FAILED:
  REQUIRE( isApproxEqual(results(i), std_result) )
with expansion:
  false
with messages:
  testing acc:alpaka::AccGpuUniformCudaHipRt<alpaka::ApiCudaRt, std::
  integral_constant<unsigned long, 1ul>, unsigned long> data type:alpaka::
  internal::Complex<float> functor:mathtest::OpPowComplex seed:4140714306
  Operator: OpPowComplex
  Type: alpaka::internal::Complex<float>
  The args buffer: 
  capacity: 1000
  0: [ (1e+01,1e+01), (0,0) ]
  ...
  999: [ (2,2), (-0.8,-0.3) ]
  
  Idx i: 1 computed : (506.109,-1.62104e+06) vs expected: (509.202,-1.62104e+
  06)
===============================================================================
test cases:    278 |    277 passed | 1 failed
assertions: 267086 | 267085 passed | 1 failed
```

Any ideas what may have caused it or how to reproduce it ?

2024-09-19 07:50 UTC, psychocoderHPC commented
I retriggered the failing test

2024-09-19 11:38 UTC, fwyzard requested changes
After reviewing the behaviour of HIP with @AuroraPerego, we think that all AMD GPUs starting from gfx 10.0 should support only a subgroup size of 32.

2024-09-19 12:21 UTC, psychocoderHPC commented
> After reviewing the behaviour of HIP with @AuroraPerego, we think that all AMD GPUs starting from gfx 10.0 should support only a subgroup size of 32.

Yes I checked it against https://rocm.docs.amd.com/en/latest/reference/gpu-arch-specs.html#accelerator-and-gpu-hardware-specifications (the table has different tabs)

and AMD is writing https://rocm.docs.amd.com/projects/HIP/en/latest/understand/hardware_implementation.html#rdna-architecture

```
RDNA makes a fundamental change to CU design, by changing the size of a warp to 32 threads. This is done by effectively combining two GCN5 SIMDs, creating a VALU of width 32, so that a whole warp can be issued in one cycle. The CU is also replaced by the work group processor (WGP), which encompasses two CUs. For backwards compatibility the WGP can also run in wave64 mode, in which it issues a warp of size 64 in two cycles.
```

2024-09-19 13:11 UTC, fwyzard commented
Yes... the RDNA1, RDNA2 and [RDNA3](https://www.amd.com/content/dam/amd/en/documents/radeon-tech-docs/instruction-set-architectures/rdna3-shader-instruction-set-architecture-feb-2023_0.pdf) architecture whitepapers suggest that both 32 and 64 can be used.

And `clang++` does have an `-mwavefrontsize64` option to enable wavefronts (warps) with 64 elements.

But HIP does not like it:
##### `/opt/rocm/include/hip/hip_runtime.h`
```c++
#if __HIP_DEVICE_COMPILE__ && !__GFX7__ && !__GFX8__ && !__GFX9__ && __AMDGCN_WAVEFRONT_SIZE == 64
#error HIP is not supported on the specified GPU ARCH with wavefront size 64
#endif
```

I assume that the ROCm backend for SYCL/oneAPI is built with HIP, so on gfx 10 and later we should use only a wavefront size of 32.

2024-09-19 13:24 UTC, fwyzard commented on include/alpaka/kernel/SyclSubgroupSize.hpp
> +
```suggestion
            (__SYCL_TARGET_INTEL_GPU_EHL__) || /* Elkhart Lake or Jasper Lake Intel graphics architecture */          \
            (__SYCL_TARGET_INTEL_GPU_TGLLP__) || /* Tiger Lake Intel graphics architecture */                         \
            (__SYCL_TARGET_INTEL_GPU_RKL__) || /* Rocket Lake Intel graphics architecture */                          \
            (__SYCL_TARGET_INTEL_GPU_ADL_S__) || /* Alder Lake S or Raptor Lake S Intel graphics architecture */      \
            (__SYCL_TARGET_INTEL_GPU_ADL_P__) || /* Alder Lake P Intel graphics architecture */                       \
            (__SYCL_TARGET_INTEL_GPU_ADL_N__) || /* Alder Lake N Intel graphics architecture */                       \
            (__SYCL_TARGET_INTEL_GPU_DG1__) || /* DG1 Intel graphics architecture */                                  \
            (__SYCL_TARGET_INTEL_GPU_ACM_G10__) || /* Alchemist G10 Intel graphics architecture */                    \
            (__SYCL_TARGET_INTEL_GPU_ACM_G11__) || /* Alchemist G11 Intel graphics architecture */                    \
            (__SYCL_TARGET_INTEL_GPU_ACM_G12__) || /* Alchemist G12 Intel graphics architecture */                    \
            (__SYCL_TARGET_INTEL_GPU_MTL_U__) || /* Meteor Lake U/S or Arrow Lake U/S Intel graphics architecture */  \
            (__SYCL_TARGET_INTEL_GPU_MTL_H__) || /* Meteor Lake H Intel graphics architecture */                      \
            (__SYCL_TARGET_INTEL_GPU_ARL_H__) || /* Arrow Lake H Intel graphics architecture */                       \
            (__SYCL_TARGET_INTEL_GPU_BMG_G21__) || /* Battlemage G21 Intel graphics architecture */                   \
            (__SYCL_TARGET_INTEL_GPU_LNL_M__) /* Lunar Lake Intel graphics architecture */
```

To keep the same order as in `sycl/doc/UsersManual.md`

2024-09-19 13:28 UTC, fwyzard commented on include/alpaka/kernel/SyclSubgroupSize.hpp
> +            (__SYCL_TARGET_AMD_GPU_GFX942__) /* AMD CDNA 3.0 Instinct architecture (gfx 9.4) */
```suggestion
           (__SYCL_TARGET_AMD_GPU_GFX909__) || /* AMD GCN 5.0 Raven 2 architecture (gfx 9.0) */                      \
            (__SYCL_TARGET_AMD_GPU_GFX90A__) || /* AMD CDNA 2.0 Aldebaran architecture (gfx 9.0) */                   \
            (__SYCL_TARGET_AMD_GPU_GFX90C__) || /* AMD GCN 5.1 Renoir architecture (gfx 9.0) */                       \
            (__SYCL_TARGET_AMD_GPU_GFX940__) || /* AMD CDNA 3.0 Aqua Vanjaram architecture (gfx 9.4) */               \
            (__SYCL_TARGET_AMD_GPU_GFX941__) || /* AMD CDNA 3.0 Aqua Vanjaram architecture (gfx 9.4) */               \
            (__SYCL_TARGET_AMD_GPU_GFX942__) /* AMD CDNA 3.0 Aqua Vanjaram architecture (gfx 9.4) */
```

2024-09-19 13:30 UTC, fwyzard commented on include/alpaka/kernel/SyclSubgroupSize.hpp
> +            (__SYCL_TARGET_AMD_GPU_GFX1200__) || /* AMD RDNA 4.0 Navi 48 architecture (gfx 12.0) */                   \
```suggestion
            (__SYCL_TARGET_AMD_GPU_GFX1033__) || /* AMD RDNA 2.0 Van Gogh architecture (gfx 10.3) */                  \
            (__SYCL_TARGET_AMD_GPU_GFX1034__) || /* AMD RDNA 2.0 Navi 24 architecture (gfx 10.3) */                   \
            (__SYCL_TARGET_AMD_GPU_GFX1035__) || /* AMD RDNA 2.0 Rembrandt Mobile architecture (gfx 10.3) */          \
            (__SYCL_TARGET_AMD_GPU_GFX1036__) || /* AMD RDNA 2.0 Raphael architecture (gfx 10.3) */                   \
            (__SYCL_TARGET_AMD_GPU_GFX1100__) || /* AMD RDNA 3.0 Navi 31 architecture (gfx 11.0) */                   \
            (__SYCL_TARGET_AMD_GPU_GFX1101__) || /* AMD RDNA 3.0 Navi 32 architecture (gfx 11.0) */                   \
            (__SYCL_TARGET_AMD_GPU_GFX1102__) || /* AMD RDNA 3.0 Navi 33 architecture (gfx 11.0) */                   \
            (__SYCL_TARGET_AMD_GPU_GFX1103__) || /* AMD RDNA 3.0 Phoenix mobile architecture (gfx 11.0) */            \
            (__SYCL_TARGET_AMD_GPU_GFX1150__) || /* AMD RDNA 3.5 Strix Point architecture (gfx 11.5) */               \
            (__SYCL_TARGET_AMD_GPU_GFX1151__) || /* AMD RDNA 3.5 Strix Halo architecture (gfx 11.5) */                \
            (__SYCL_TARGET_AMD_GPU_GFX1200__) || /* AMD RDNA 4.0 Navi 44 architecture (gfx 12.0) */                   \
```

2024-09-19 13:51 UTC, fwyzard approved these changes

2024-09-20 13:31 UTC, psychocoderHPC approved these changes

2024-09-20 13:31 UTC, merged