Single thread acc throw for invalid workdiv fix
alpaka-group/alpaka pull request #2391
Opened 2024-09-23 07:35 UTC by ikbuibui

For a single thread acc if the WorkDiv number of threads per block is more than one, throw a runtime error
We now throw in create task kernel. The current approach of throwing when the task kernel is executed doesn't work. ``CallbackThread::startWorkerThread``, tries to handle the  exception, but it needs to be dealt with the thread that creates it.

2024-09-23 09:37 UTC, fwyzard submitted a review, later dismissed

2024-09-23 09:37 UTC, fwyzard commented
LGTM

2024-09-23 12:23 UTC, psychocoderHPC requested changes

2024-09-23 12:23 UTC, psychocoderHPC commented on include/alpaka/acc/AccCpuOmp2Blocks.hpp
> +                if(workDiv.m_blockThreadExtent.prod() != static_cast<TIdx>(1u))
please remove the checks in the `operator()` no need to keep the old checks if we can not catch the exception.

2024-09-23 13:08 UTC, ikbuibui commented on include/alpaka/acc/AccCpuOmp2Blocks.hpp
> +                if(workDiv.m_blockThreadExtent.prod() != static_cast<TIdx>(1u))
Fixed

2024-09-24 10:59 UTC, psychocoderHPC approved these changes

2024-09-24 11:00 UTC, merged