use rocBLAS from alpaka
alpaka-group/alpaka pull request #2433
Opened 2024-11-28 17:52 UTC by mehmetyusufoglu

2024-12-10 09:04 UTC, psychocoderHPC commented
IMO we should provide a subfolder in the example folder and add the rocm and cuda examples there in.

suggested name: nativeAPI

2025-02-25 09:01 UTC, psychocoderHPC requested changes

2025-02-25 09:01 UTC, psychocoderHPC commented on example/useBLASInAlpaka/useRocBLASInAlpaka/src/useRocBLASInAlpaka.cpp
> +    float alpha = 1.0f, beta = 0.0f;
please choose a value different to 1.0 and 0.0 for the Constance.

2025-03-04 09:25 UTC, mehmetyusufoglu commented on example/useBLASInAlpaka/useRocBLASInAlpaka/src/useRocBLASInAlpaka.cpp
> +    float alpha = 1.0f, beta = 0.0f;
I have implemented matrix multiplication, therefore beta is 0.0. Either i can add a comment or chose beta nonzero and say that this is a linear operation not multiplication inside the comments and outputs.

2025-03-06 08:26 UTC, psychocoderHPC commented on example/useBLASInAlpaka/useRocBLASInAlpaka/src/useRocBLASInAlpaka.cpp
> +    float alpha = 1.0f, beta = 0.0f;
Ahh ok, in that case the comment should be adjusted and say that alpaha is 1 and beta zero because you a pure matrix multiplication is performed.

2025-03-06 13:55 UTC, mehmetyusufoglu commented on example/useBLASInAlpaka/useRocBLASInAlpaka/src/useRocBLASInAlpaka.cpp
> +    float alpha = 1.0f, beta = 0.0f;
done, thanks.

2025-03-13 09:27 UTC, psychocoderHPC approved these changes

2025-03-13 09:27 UTC, merged