Add support for clang 8.0
alpaka-group/alpaka pull request #769
Opened 2019-03-27 17:27 UTC by BenjaminW3

2019-03-27 18:20 UTC, bertwesarg commented
> Furthermore it warns on empty expressions due to useless `;`. This was the case for some of our usages of test macros.

The trick here is to change the macros not the callsite:

```C++
#define ALPAKA_CHECK(success, expression) \
    do \
    { \
        if(!(expression)) \
        { \
            printf("ALPAKA_CHECK failed because '!(%s)'\n", #expression); \
            success = false; \
        } \
    } while ( 0 )
```

Now it requires a ';' and it could be converted to an no-op:
 
```C++
#define ALPAKA_CHECK(success, expression) do { } while ( 0 )
```

2019-03-27 18:24 UTC, BenjaminW3 commented
Yes, this would also work, but I do not yet see an advantage of introducing more syntax elements just to silence this warning ;-)

2019-03-27 18:27 UTC, bertwesarg commented
> Yes, this would also work, but I do not yet see an advantage of introducing more syntax elements just to silence this warning ;-)

But my proposal would result in a much smaller patch, and the misusage of the macro would be cought by all compilers. It also is more pleasing to the programmer eyes, as _function calls_ without a terminating ';' look odd.

2019-03-28 12:20 UTC, psychocoderHPC commented
> > Furthermore it warns on empty expressions due to useless `;`. This was the case for some of our usages of test macros.
> 
> The trick here is to change the macros not the callsite:
> 
> ```c++
> #define ALPAKA_CHECK(success, expression) \
>     do \
>     { \
>         if(!(expression)) \
>         { \
>             printf("ALPAKA_CHECK failed because '!(%s)'\n", #expression); \
>             success = false; \
>         } \
>     } while ( 0 )
> ```
> 
> Now it requires a ';' and it could be converted to an no-op:
> 
> ```c++
> #define ALPAKA_CHECK(success, expression) do { } while ( 0 )
> ```

I do not like the C way to add a while loop to enforce a semicolon. I prefer the shorter version

```C++
#define FOO() \
{           \
// code     \
}           \
( (void) 0 )
```

2019-03-28 12:22 UTC, psychocoderHPC commented
@BenjaminW3 I would also prefere to keep the semicolon after a macro, else it looks not natureal and you need alsways to know where you must/can add a semicolon.

2019-03-28 12:25 UTC, psychocoderHPC requested changes

2019-03-28 12:25 UTC, psychocoderHPC commented on test/unit/atomic/src/AtomicTest.cpp
> +    ALPAKA_CHECK(*success, operandOrig == ret)
please reintroduce the semicolon and enforce it with `do{}while(true)` or `((void) 0)`

2019-03-28 12:25 UTC, bertwesarg commented
> ```c++
> #define FOO() \
> {           \
> // code     \
> }           \
> ( (void) 0 )
> ```

Duh, that are **two** statements. Even though your coding style requires always **oc-tokens** around _blocks_, it can't be enforced. Only GCC warns about macros which have multiple statements and are used as _blocks_. I.e.,

```c++
if ( foo )
    FOO();
```

2019-03-28 12:27 UTC, psychocoderHPC commented
@bertwesarg Yes you are right, I missed that important point.

2019-03-28 20:31 UTC, bertwesarg commented
lgtm now

2019-03-28 20:32 UTC, bertwesarg approved these changes

2019-03-29 08:39 UTC, psychocoderHPC approved these changes

2019-03-29 08:39 UTC, psychocoderHPC commented
thx for the update!

2019-03-29 08:39 UTC, merged