math/abs: Added trait specialisation for double.
alpaka-group/alpaka pull request #862
Opened 2019-10-18 14:52 UTC by jkrude

In include/alpaka/math/abs:
Int is also supported in cuda/hip, so fabs is used for double type.
abs for int
fabs for double <-- was missing
fabsf for float

2019-10-18 16:06 UTC, BenjaminW3 submitted a review, later dismissed

2019-10-22 14:06 UTC, ax3l submitted a review, later dismissed

2019-10-22 14:09 UTC, ax3l commented on include/alpaka/math/abs/AbsCudaBuiltIn.hpp
> +            }
```suggestion
            };
```

2019-10-23 08:16 UTC, psychocoderHPC commented
@jkrude  I stopped the CI because the first tests failed so that we can test also other pull requests:

errors:
- https://travis-ci.org/ComputationalRadiationPhysics/alpaka/jobs/601684451#L2822
- https://travis-ci.org/ComputationalRadiationPhysics/alpaka/jobs/601684453#L5673-L5687

2019-10-23 09:16 UTC, sbastrakov commented on include/alpaka/math/abs/AbsCudaBuiltIn.hpp
> +                    TArg const & arg)
Sorry it went unnoticed before, here `TArg` should be replaced with `double`.

2019-10-23 09:16 UTC, sbastrakov requested changes

2019-10-23 09:16 UTC, sbastrakov commented on include/alpaka/math/abs/AbsHipBuiltIn.hpp
> +                    TArg const & arg)
Here as well.

2019-10-23 09:32 UTC, sbastrakov approved these changes

2019-10-23 09:42 UTC, psychocoderHPC approved these changes

2019-10-24 11:56 UTC, merged