Refactor CI scripts
alpaka-group/alpaka pull request #976
Opened 2020-04-11 06:13 UTC by BenjaminW3

* install and execute shellcheck and sloc also on mac
* Split generate and build phase as this is more idiomatic

2020-04-14 06:43 UTC, psychocoderHPC requested changes
only a little change needed

2020-04-14 06:43 UTC, psychocoderHPC commented on script/install_analysis.sh
> +fi
Could you please at a empty line.

2020-04-14 06:55 UTC, BenjaminW3 commented on script/install_analysis.sh
> +fi
done

2020-04-15 12:27 UTC, BenjaminW3 commented
Please approve again. Build is green now.

2020-04-15 12:51 UTC, psychocoderHPC approved these changes

2020-04-15 12:51 UTC, merged